<?php

/**
 * @file
 * PHPUnit bootstrap for myapi unit tests.
 *
 * Lets tests `require` production .inc/.resource.inc files directly, outside
 * Drupal, with no copies. The only Drupal-level call these files make at file
 * scope (not inside a function) is module_load_include(), used by
 * resources/auth.resource.inc to pull in its includes/*.inc dependencies; this
 * stub makes that call a no-op so the require succeeds. Tests still `require`
 * the specific includes/*.inc files they actually exercise.
 *
 * If a future change adds another file-scope call to a Drupal function in one
 * of the .inc files exercised by tests/unit, this stub needs to grow to cover
 * it too — see tests/README.md.
 *
 * The four text helpers below (SPEC 50) are a different kind of stub: they are
 * called from INSIDE the functions under test, not at file scope, and each one
 * is a faithful one-line equivalent of the Drupal function for the only use
 * the tested code makes of it. They exist so the cancellation-reason texts can
 * be asserted character by character. Nothing here touches the database: the
 * suite still covers pure logic only.
 *
 * t() and form_set_error() (SPEC 52) are of that same kind, and are what makes
 * myapi_time_format_validate_fields() testable without a site: the walker is
 * shared by the 'area' and 'reservation' node forms, so one bug in it silences
 * the validation of four fields at once.
 *
 * drupal_get_path() and $base_url (SPEC 54) are the environment counterpart:
 * myapi_mail_logo_url() builds the header logo URL out of both, and every HTML
 * email template calls it, so without them the whole email suite fatals.
 *
 * element_children() (SPEC 59) is the same kind again: the only Drupal function
 * myapi_claim_transaction_transaction_form_alter() calls from inside, to walk
 * the langcode/delta levels of the field_claim widget.
 *
 * truncate_utf8() and drupal_substr() (SPEC 60) are what let the autogenerated
 * title of a 'claim_transaction' be asserted character by character: the title
 * cuts the operator's comment at 60 characters without breaking a word, and
 * that cut is core's, not myapi's.
 *
 * variable_get() and url() (SPEC 73) are the last of the Drupal kind: the reset
 * page reads its deep-link base out of a variable and builds its form action
 * with url(), and neither has any meaning outside a site.
 *
 * variable_get() and url() (SPEC 73) are the last of the Drupal kind: the reset
 * page reads its deep-link base out of a variable and builds its form action
 * with url(), and neither has any meaning outside a site.
 *
 * drupal_exit(), drupal_add_http_header() and drupal_json_encode() (SPEC 73)
 * are the three that opened the biggest door in this suite. Everything that
 * ANSWERS in this module — myapi_respond(), myapi_error(), and through them
 * every dispatcher and the password/reset page — ends by printing a body and
 * calling drupal_exit(). Stubbing that trio means the real helpers can run
 * here: the body goes to an output buffer, the status goes to a recorded
 * header, and the "and then the request ends" becomes a thrown MyapiExit.
 * myapi_test_capture() below is the only place that knows this, and no test
 * asserts against a reimplementation of the envelope — they assert against the
 * envelope production actually prints.
 *
 * ip_address() and the three Flood API functions (SPEC 73) are the same idea
 * for the brute-force helpers: myapi_flood_is_allowed() and
 * myapi_flood_register() are pure arithmetic over Drupal variables, and what is
 * worth testing about them is precisely the arguments they hand to
 * flood_is_allowed()/flood_register_event(). The stubs record every call so a
 * test can read them back.
 *
 * myapi_user_fetch_profile_fields() (SPEC 73) is the one stub in this file that
 * replaces a MYAPI function rather than a Drupal one, and it carries a cost
 * worth stating: because the real definition in includes/myapi.user.inc is not
 * function_exists()-guarded, a future test file that require's that .inc will
 * fatal with "Cannot redeclare". That is deliberate — the real function is four
 * LEFT JOINs and belongs to tests/integration — but whoever hits that fatal
 * should read this block, not fight the guard.
 *
 * db_select(), user_load() and REQUEST_TIME (SPEC 74) are the newest kind and
 * the one that needs the loudest disclaimer. db_select() here is a FIXTURE
 * QUERY BUILDER, not a database: the rows a test seeds with
 * myapi_test_db_seed() are what execute() answers, after applying the
 * conditions and the ORDER BY over the columns the fixture carries and
 * projecting the fields/aliases the query asked for. What that makes testable
 * is the PHP half of a resource — the loops that turn rows into a response,
 * the delta precedence, the name fallbacks, the maps — running as production
 * runs it. What it does NOT do is execute SQL: joins are recorded, never
 * resolved (a joined column is seeded flat on the row, under the alias the
 * query gives it), and a condition on a column the fixture does not carry is
 * not applied. Everything SQL decides on its own — that a LEFT JOIN to a
 * multi-value field duplicates rows, that a real ORDER BY is what makes the
 * delta loop correct — stays tests/integration's job. Every query is recorded
 * in $GLOBALS['myapi_test_db_queries'] so a test can assert the SHAPE it built
 * (table, conditions, joins, order) where it cannot assert the SQL's outcome.
 */

if (!function_exists('module_load_include')) {
  function module_load_include($type, $module, $name = NULL) {
    // No-op: unit tests require the relevant includes/*.inc files themselves.
  }
}

/**
 * The two halves of the logo URL myapi_mail_logo_url() assembles.
 *
 * Drupal resolves the path from the system table and $base_url from the
 * request; outside a site both are just constants, and the value only has to
 * be stable and plausible: no assertion reads the <img> src, it is the fatal
 * on the missing function that the tests need gone.
 */
if (!function_exists('drupal_get_path')) {
  function drupal_get_path($type, $name) {
    return 'sites/all/modules/' . $name;
  }
}

$GLOBALS['base_url'] = 'https://crespcord.example.com';

if (!function_exists('drupal_strlen')) {
  function drupal_strlen($text) {
    return mb_strlen($text, 'UTF-8');
  }
}

if (!function_exists('check_plain')) {
  function check_plain($text) {
    return htmlspecialchars($text, ENT_QUOTES, 'UTF-8');
  }
}

if (!function_exists('decode_entities')) {
  function decode_entities($text) {
    return html_entity_decode($text, ENT_QUOTES, 'UTF-8');
  }
}

if (!function_exists('format_date')) {
  /**
   * Only the 'custom' type is stubbed: it is the only one myapi calls, and it
   * maps straight onto date(). The site timezone is irrelevant here because
   * every fixture builds its timestamp with mktime() in the same one.
   */
  function format_date($timestamp, $type = 'medium', $format = '', $timezone = NULL, $langcode = NULL) {
    return date($format, $timestamp);
  }
}

if (!function_exists('drupal_substr')) {
  function drupal_substr($text, $start, $length = NULL) {
    return $length === NULL
      ? mb_substr($text, $start, NULL, 'UTF-8')
      : mb_substr($text, $start, $length, 'UTF-8');
  }
}

if (!function_exists('truncate_utf8')) {
  /**
   * Core's algorithm (includes/unicode.inc), reproduced (SPEC 60): the ellipsis
   * discounts its own character from the budget, $min_wordsafe_length bounds the
   * word-safe search, and a string with no boundary in range is cut hard.
   *
   * One declared divergence: core finds the cut with its own
   * PREG_CLASS_UNICODE_WORD_BOUNDARY character class, this uses '\s'. Every
   * fixture in ClaimTransactionTitleTest cuts on a plain space, where the two
   * agree; a fixture cutting on a hyphen or a comma would not, and that is why
   * none does.
   */
  function truncate_utf8($string, $max_length, $wordsafe = FALSE, $add_ellipsis = FALSE, $min_wordsafe_length = 1) {
    $ellipsis = '';
    $max_length = max($max_length, 0);
    $min_wordsafe_length = max($min_wordsafe_length, 0);

    if (drupal_strlen($string) <= $max_length) {
      return $string;
    }

    if ($add_ellipsis) {
      $ellipsis = drupal_substr('…', 0, $max_length);
      $max_length = max($max_length - drupal_strlen($ellipsis), 0);
    }

    if ($max_length <= $min_wordsafe_length) {
      $wordsafe = FALSE;
    }

    $matches = array();
    if ($wordsafe && preg_match('/^(.{' . $min_wordsafe_length . ',' . $max_length . '})\s/u', $string, $matches)) {
      $string = $matches[1];
    }
    else {
      $string = drupal_substr($string, 0, $max_length);
    }

    return $string . $ellipsis;
  }
}

if (!function_exists('t')) {
  /**
   * The placeholder substitution only: no string catalogue is involved outside
   * Drupal, and every myapi caller passes '@name' style placeholders, which
   * Drupal itself resolves with strtr() after check_plain(). Sanitisation is
   * left out on purpose — the tested code asserts the message text, and
   * escaping it here would only make the assertions harder to read.
   */
  function t($string, array $args = [], array $options = []) {
    return $args ? strtr($string, $args) : $string;
  }
}

if (!function_exists('form_set_error')) {
  /**
   * Records the error instead of touching a form: Drupal keeps these in a
   * static and prints them on the next page load, which is not observable from
   * a unit test. The recorded map is keyed by the element path exactly as the
   * production code builds it, so a test can assert WHICH input would be
   * flagged and not just how many errors came out.
   *
   * Tests reset $GLOBALS['myapi_test_form_errors'] in setUp(); the null
   * coalescing keeps a stray call outside a test from fataling.
   */
  function form_set_error($name = NULL, $message = '') {
    $GLOBALS['myapi_test_form_errors'] = $GLOBALS['myapi_test_form_errors'] ?? [];
    $GLOBALS['myapi_test_form_errors'][$name] = $message;
    return $GLOBALS['myapi_test_form_errors'];
  }
}

if (!function_exists('element_children')) {
  /**
   * Every key that is not a '#property'. Drupal's own version also sorts by
   * '#weight' when asked; myapi never asks, and the widget's deltas are
   * already in order, so the sort is left out on purpose.
   *
   * The is_int() branch is the PHP 7.4 guard: field widget deltas are integer
   * keys, and $key[0] on an int raises "Trying to access array offset on value
   * of type int". An integer key is never a '#property', so short-circuiting
   * on it is faithful to the original rather than a deviation from it.
   */
  function element_children(&$elements, $sort = FALSE) {
    $children = array();
    foreach ($elements as $key => $value) {
      if (is_int($key) || $key === '' || $key[0] !== '#') {
        $children[] = $key;
      }
    }

    return $children;
  }
}

if (!function_exists('variable_get')) {
  /**
   * Reads from an in-memory map instead of the variables table (SPEC 73).
   *
   * Faithful for the only thing myapi asks of it: a site with no override
   * answers the default the call site passed, which is exactly what a test
   * asserting the shipped behaviour wants. A test that needs the overridden
   * branch sets $GLOBALS['myapi_test_variables'][$name] first and resets the
   * map in tearDown(), the same way a site administrator would set the
   * variable and the same way Drupal would then return it.
   */
  function variable_get($name, $default = NULL) {
    return isset($GLOBALS['myapi_test_variables'][$name])
      ? $GLOBALS['myapi_test_variables'][$name]
      : $default;
  }
}

if (!function_exists('url')) {
  /**
   * The root-relative half of Drupal's url() (SPEC 73).
   *
   * Two declared divergences, neither reachable from the code under test: path
   * aliases are not resolved (myapi passes system paths only), and 'absolute'
   * is ignored (the reset form posts to itself, relatively). What IS faithful
   * is the query string, which is the part the tests assert: Drupal builds it
   * with drupal_http_build_query(), whose difference from http_build_query()
   * is the encoding of the '/' character — no myapi query value contains one.
   */
  function url($path = NULL, array $options = []) {
    $url = '/' . ltrim((string) $path, '/');

    if (!empty($options['query'])) {
      $url .= '?' . http_build_query($options['query']);
    }

    return $url;
  }
}

/**
 * The end of the request, as an exception (SPEC 73).
 *
 * drupal_exit() does not return, and neither does anything that calls it. The
 * throw is what reproduces that here: the code after a myapi_error() call
 * never runs in a test either, exactly as it never runs in production.
 */
class MyapiExit extends RuntimeException {
}

if (!function_exists('drupal_exit')) {
  function drupal_exit($destination = NULL) {
    throw new MyapiExit('drupal_exit()');
  }
}

if (!function_exists('drupal_add_http_header')) {
  /**
   * Records the header instead of sending it.
   *
   * Drupal keeps these in a static and flushes them with the response, which
   * is not observable from a unit test. The recorded map is what lets a test
   * assert the STATUS CODE of a response — 401 vs 422 vs 429 is half of this
   * API's contract, and asserting the body alone would miss it entirely.
   */
  function drupal_add_http_header($name, $value, $append = FALSE) {
    $GLOBALS['myapi_test_http_headers'][$name] = $value;
  }
}

if (!function_exists('drupal_json_encode')) {
  /**
   * Core's own (includes/common.inc), reproduced: json_encode() with the four
   * JSON_HEX_* flags that escape <, >, ' and & so a JSON response is safe to
   * embed in HTML.
   *
   * Faithful rather than convenient on purpose: the flags change the BYTES of
   * every response this module sends, and a test asserting a raw body would
   * silently disagree with production if this used a plain json_encode().
   */
  function drupal_json_encode($var) {
    return json_encode($var, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT);
  }
}

if (!function_exists('ip_address')) {
  function ip_address() {
    return isset($GLOBALS['myapi_test_ip']) ? $GLOBALS['myapi_test_ip'] : '203.0.113.7';
  }
}

if (!function_exists('flood_is_allowed')) {
  /**
   * Answers what the test told it to, and records how it was asked.
   *
   * The real one counts rows in the {flood} table, which is not what
   * myapi_flood_is_allowed() is responsible for. What IS its responsibility is
   * resolving a limit and a window out of two Drupal variable names and
   * passing them here in the right order — a threshold and a window swapped,
   * or a variable name misspelled, produces a silently wrong rate limit and no
   * error anywhere. Recording the arguments is what makes that assertable.
   */
  function flood_is_allowed($name, $threshold, $window = 3600, $identifier = NULL) {
    $GLOBALS['myapi_test_flood_calls'][] = [
      'call'       => 'is_allowed',
      'event'      => $name,
      'threshold'  => $threshold,
      'window'     => $window,
      'identifier' => $identifier,
    ];

    return isset($GLOBALS['myapi_test_flood_allowed']) ? $GLOBALS['myapi_test_flood_allowed'] : TRUE;
  }
}

if (!function_exists('flood_register_event')) {
  function flood_register_event($name, $window = 3600, $identifier = NULL) {
    $GLOBALS['myapi_test_flood_calls'][] = [
      'call'       => 'register',
      'event'      => $name,
      'window'     => $window,
      'identifier' => $identifier,
    ];
  }
}

if (!function_exists('flood_clear_event')) {
  function flood_clear_event($name, $identifier = NULL) {
    $GLOBALS['myapi_test_flood_calls'][] = [
      'call'       => 'clear',
      'event'      => $name,
      'identifier' => $identifier,
    ];
  }
}

/**
 * Runs a responder and returns everything it produced (SPEC 73).
 *
 * The single seam between "a function that answers and ends the request" and
 * an assertion. Every caller of myapi_respond()/myapi_error(), and every
 * render path of the password/reset page, goes through here.
 *
 * The output buffer is closed in a finally block: a callable that throws
 * something other than MyapiExit — a real bug in the code under test — must
 * not leave the buffer open and swallow the rest of the suite's output.
 *
 * @param callable $callable  The dispatcher, resource function or renderer.
 *
 * @return array  'exited'  — whether the request ended (it always should),
 *                'output'  — the raw printed body,
 *                'json'    — that body decoded, or NULL when it is not JSON,
 *                'status'  — the 'Status' header as an int, or NULL,
 *                'headers' — every header the call set.
 */
function myapi_test_capture(callable $callable) {
  $GLOBALS['myapi_test_http_headers'] = [];
  $exited = FALSE;

  ob_start();
  try {
    $callable();
  }
  catch (MyapiExit $e) {
    $exited = TRUE;
  }
  finally {
    $output = ob_get_clean();
  }

  $headers = $GLOBALS['myapi_test_http_headers'];

  return [
    'exited'  => $exited,
    'output'  => $output,
    'json'    => json_decode($output, TRUE),
    'status'  => isset($headers['Status']) ? (int) $headers['Status'] : NULL,
    'headers' => $headers,
  ];
}

if (!function_exists('myapi_user_fetch_profile_fields')) {
  /**
   * Returns a caller-provided profile row instead of running the field joins.
   *
   * The real function (includes/myapi.user.inc) is four LEFT JOINs over
   * field_data_field_nombre/apellidos/cedula/telefono; there is no way to
   * exercise it without a database, and no reason to, since what SPEC 73 tests
   * is its CONSUMER: myapi_auth_build_user_payload(), the "user" sub-object
   * that login and refresh both return and must never let drift apart.
   *
   * The default is the all-NULL row the real function answers for an account
   * with no profile values — the shape a test gets when it sets nothing.
   */
  function myapi_user_fetch_profile_fields($uid) {
    $default = ['first_name' => NULL, 'last_name' => NULL, 'dni' => NULL, 'phone' => NULL];

    return isset($GLOBALS['myapi_test_profile_fields'])
      ? $GLOBALS['myapi_test_profile_fields'] + $default
      : $default;
  }
}

/**
 * The request timestamp (SPEC 74).
 *
 * Drupal defines it once per request in bootstrap.inc. Token expiry is compared
 * against it, so a fixture expressed as REQUEST_TIME +/- N seconds means the
 * same thing here as it does in production.
 */
if (!defined('REQUEST_TIME')) {
  define('REQUEST_TIME', time());
}

/**
 * A SELECT over fixtures (SPEC 74).
 *
 * Implements the subset of Drupal 7's SelectQuery that myapi's read paths
 * actually use: fields(), addField(), condition(), the join family, orderBy(),
 * range() and execute(). Anything else throws instead of returning a wrong
 * answer quietly — a resource that starts using groupBy() must extend this
 * class knowingly, not discover that its test passed for the wrong reason.
 *
 * The rules, in full:
 *  - The base table names the fixture: myapi_test_db_seed(['node' => [...]])
 *    is what a SELECT ... FROM node reads.
 *  - Conditions are applied over the fixture's own columns, with the alias
 *    prefix stripped ('n.status' matches the 'status' key). A condition on a
 *    column the fixture row does not carry is skipped, which is what lets a
 *    test seed only the columns its case is about.
 *  - Joins are recorded, never resolved. A joined column is seeded flat on the
 *    row under the alias the query gives it ('area_m2', not
 *    'field_total_m2_value'), because that alias is what production reads off
 *    the result.
 *  - The projection is the field list: each requested field/alias is copied
 *    from the row when present and NULL otherwise, in the order it was added.
 *    fields($alias) with no column list selects the row whole, as in Drupal.
 */
class MyapiTestSelectQuery implements IteratorAggregate {

  private $table;
  private $alias;
  private $fields = [];
  private $select_all = FALSE;
  private $conditions = [];
  private $where = [];
  private $joins = [];
  private $order = [];
  private $range = NULL;
  private $count_mode = FALSE;

  public function __construct($table, $alias) {
    $this->table = $table;
    $this->alias = $alias;
  }

  public function fields($table_alias, array $fields = []) {
    if (empty($fields)) {
      $this->select_all = TRUE;
    }
    foreach ($fields as $field) {
      $this->fields[] = $field;
    }

    return $this;
  }

  public function addField($table_alias, $field, $alias = NULL) {
    $this->fields[] = $alias !== NULL ? $alias : $field;

    return $this;
  }

  public function condition($field, $value = NULL, $operator = NULL) {
    if (!is_string($field)) {
      throw new RuntimeException('MyapiTestSelectQuery: only string conditions are supported.');
    }
    $this->conditions[] = [
      'field'    => $field,
      'value'    => $value,
      'operator' => $operator !== NULL ? strtoupper($operator) : (is_array($value) ? 'IN' : '='),
    ];

    return $this;
  }

  public function isNull($field) {
    $this->conditions[] = ['field' => $field, 'value' => NULL, 'operator' => 'IS NULL'];

    return $this;
  }

  public function isNotNull($field) {
    $this->conditions[] = ['field' => $field, 'value' => NULL, 'operator' => 'IS NOT NULL'];

    return $this;
  }

  /**
   * A raw SQL fragment, of the one shape myapi actually writes (SPEC 75).
   *
   * Every where() in this module is a date-range bound of the form
   *
   *   SUBSTR(alias.column, 1, 10) >= :date_from
   *
   * and that shape is parsed and APPLIED here rather than merely recorded,
   * because the date filter is half of what SPEC 15 promises keeps working
   * when pagination is switched off — a recorded-but-ignored bound would let
   * limit=-1 "return everything" past a filter that never ran.
   *
   * The SUBSTR is honoured literally (the stored value is a datetime and the
   * bound is a date, so the cut is what makes them comparable), and the
   * comparison reuses compare(), the same operator table the conditions use.
   *
   * Anything that is not that shape throws instead of being skipped quietly:
   * a resource that starts writing a different fragment must teach this parser
   * about it, not discover that its test passed because the bound evaporated.
   */
  public function where($snippet, array $arguments = []) {
    $pattern = '/^SUBSTR\(\s*([A-Za-z0-9_.]+)\s*,\s*1\s*,\s*(\d+)\s*\)\s*(>=|<=|<>|!=|=|<|>)\s*(:[A-Za-z0-9_]+)\s*$/';

    if (!preg_match($pattern, trim($snippet), $m)) {
      throw new RuntimeException('MyapiTestSelectQuery: unsupported where() fragment "' . $snippet . '".');
    }
    if (!array_key_exists($m[4], $arguments)) {
      throw new RuntimeException('MyapiTestSelectQuery: where() placeholder ' . $m[4] . ' has no argument.');
    }

    $this->where[] = [
      'snippet'   => $snippet,
      'arguments' => $arguments,
      'field'     => $m[1],
      'length'    => (int) $m[2],
      'operator'  => $m[3] === '!=' ? '<>' : $m[3],
      'value'     => $arguments[$m[4]],
    ];

    return $this;
  }

  /**
   * The row count of the same filtered set (SPEC 75).
   *
   * Drupal's countQuery() returns a NEW query that drops the field list, the
   * ordering and the range and answers a single COUNT(*) column; the clone
   * here does the same, which is what makes 'pagination.total' independent of
   * the page being fetched. Dropping the range is the part that matters: a
   * count that inherited it would answer the size of the page instead of the
   * size of the set, and every total_pages assertion would agree with itself
   * while being wrong.
   */
  public function countQuery() {
    $count = clone $this;
    $count->count_mode = TRUE;
    $count->fields = [];
    $count->select_all = FALSE;
    $count->order = [];
    $count->range = NULL;

    return $count;
  }

  public function leftJoin($table, $alias = NULL, $condition = NULL) {
    return $this->addJoin('LEFT', $table, $alias, $condition);
  }

  public function innerJoin($table, $alias = NULL, $condition = NULL) {
    return $this->addJoin('INNER', $table, $alias, $condition);
  }

  public function join($table, $alias = NULL, $condition = NULL) {
    return $this->addJoin('INNER', $table, $alias, $condition);
  }

  private function addJoin($type, $table, $alias, $condition) {
    $this->joins[] = ['type' => $type, 'table' => $table, 'alias' => $alias, 'condition' => $condition];

    return $alias;
  }

  public function orderBy($field, $direction = 'ASC') {
    $this->order[] = ['field' => $field, 'direction' => strtoupper($direction)];

    return $this;
  }

  public function range($start = NULL, $length = NULL) {
    $this->range = ['start' => (int) $start, 'length' => $length];

    return $this;
  }

  public function __call($name, $arguments) {
    throw new RuntimeException('MyapiTestSelectQuery: ' . $name . '() is not supported by the fixture query builder.');
  }

  #[\ReturnTypeWillChange]
  public function getIterator() {
    return new ArrayIterator($this->rows());
  }

  /**
   * Records the query and answers the fixture rows it selects.
   */
  public function execute() {
    $GLOBALS['myapi_test_db_queries'][] = [
      'table'      => $this->table,
      'alias'      => $this->alias,
      'fields'     => $this->fields,
      'select_all' => $this->select_all,
      'conditions' => $this->conditions,
      'where'      => $this->where,
      'joins'      => $this->joins,
      'order'      => $this->order,
      'range'      => $this->range,
      'count'      => $this->count_mode,
    ];

    if ($this->count_mode) {
      // One row, one column, exactly as COUNT(*) answers — fetchField() reads
      // it positionally, so the column name is arbitrary.
      return new MyapiTestStatement([['expression' => count($this->matchedRows())]]);
    }

    return new MyapiTestStatement($this->rows());
  }

  /**
   * Filter, then order, then range, then project — the order a database
   * applies them in.
   */
  private function rows() {
    $rows = $this->sort($this->matchedRows());

    if ($this->range !== NULL) {
      $rows = array_slice($rows, $this->range['start'], $this->range['length']);
    }

    return array_map([$this, 'project'], $rows);
  }

  /**
   * The fixture rows that survive the conditions and the where() fragments,
   * before any ordering, range or projection.
   */
  private function matchedRows() {
    $rows = isset($GLOBALS['myapi_test_db'][$this->table]) ? $GLOBALS['myapi_test_db'][$this->table] : [];
    $rows = array_map(function ($row) {
      return (array) $row;
    }, $rows);

    return array_values(array_filter($rows, [$this, 'matches']));
  }

  private function matches(array $row) {
    foreach ($this->conditions as $condition) {
      $column = $this->column($condition['field']);
      if (!array_key_exists($column, $row)) {
        continue;
      }
      if (!$this->compare($row[$column], $condition['value'], $condition['operator'])) {
        return FALSE;
      }
    }

    foreach ($this->where as $fragment) {
      $column = $this->column($fragment['field']);
      if (!array_key_exists($column, $row)) {
        continue;
      }
      // NULL is what a LEFT JOIN answers for a node with no row in the joined
      // field table, and SQL compares it to nothing: a bound always excludes
      // it, which is the documented behaviour of the date filter.
      if ($row[$column] === NULL) {
        return FALSE;
      }
      $actual = substr((string) $row[$column], 0, $fragment['length']);
      if (!$this->compare($actual, $fragment['value'], $fragment['operator'])) {
        return FALSE;
      }
    }

    return TRUE;
  }

  /**
   * Loose comparison on purpose: a real result set answers '1' where a fixture
   * writes 1, and no myapi condition depends on telling the two apart.
   */
  private function compare($actual, $expected, $operator) {
    switch ($operator) {
      case '=':
        return $actual == $expected;

      case '!=':
      case '<>':
        return $actual != $expected;

      case '>':
        return $actual > $expected;

      case '>=':
        return $actual >= $expected;

      case '<':
        return $actual < $expected;

      case '<=':
        return $actual <= $expected;

      case 'IN':
        return in_array($actual, (array) $expected);

      case 'NOT IN':
        return !in_array($actual, (array) $expected);

      case 'IS NULL':
        return $actual === NULL;

      case 'IS NOT NULL':
        return $actual !== NULL;
    }

    throw new RuntimeException('MyapiTestSelectQuery: unsupported operator "' . $operator . '".');
  }

  private function sort(array $rows) {
    foreach (array_reverse($this->order) as $order) {
      $column = $this->column($order['field']);
      $direction = $order['direction'] === 'DESC' ? -1 : 1;
      // usort() is not stable in PHP 7.4, so the original position is carried
      // as the tie-breaker: two rows with the same delta keep the order the
      // fixture wrote them in.
      $indexed = [];
      foreach ($rows as $position => $row) {
        $indexed[] = [$position, $row];
      }
      usort($indexed, function ($a, $b) use ($column, $direction) {
        $left = isset($a[1][$column]) ? $a[1][$column] : NULL;
        $right = isset($b[1][$column]) ? $b[1][$column] : NULL;
        if ($left == $right) {
          return $a[0] <=> $b[0];
        }

        return ($left < $right ? -1 : 1) * $direction;
      });
      $rows = array_column($indexed, 1);
    }

    return $rows;
  }

  private function project(array $row) {
    if ($this->select_all) {
      return $row;
    }

    $projected = [];
    foreach ($this->fields as $field) {
      $projected[$field] = array_key_exists($field, $row) ? $row[$field] : NULL;
    }

    return $projected;
  }

  private function column($field) {
    $position = strpos($field, '.');

    return $position === FALSE ? $field : substr($field, $position + 1);
  }

}

/**
 * The result of a fixture SELECT (SPEC 74).
 *
 * Answers the four fetchers myapi's read paths use, plus iteration, which is
 * how most of them consume a result. Rows come out as stdClass, exactly as
 * Drupal's default fetch mode delivers them.
 */
class MyapiTestStatement implements IteratorAggregate, Countable {

  private $rows;

  public function __construct(array $rows) {
    $this->rows = $rows;
  }

  #[\ReturnTypeWillChange]
  public function getIterator() {
    return new ArrayIterator($this->fetchAll());
  }

  public function fetchAll() {
    return array_map(function ($row) {
      return (object) $row;
    }, $this->rows);
  }

  public function fetchAllAssoc($key) {
    $result = [];
    foreach ($this->fetchAll() as $row) {
      $result[$row->{$key}] = $row;
    }

    return $result;
  }

  public function fetchCol($index = 0) {
    $column = [];
    foreach ($this->rows as $row) {
      $values = array_values($row);
      $column[] = isset($values[$index]) ? $values[$index] : NULL;
    }

    return $column;
  }

  public function fetchObject() {
    $rows = $this->fetchAll();

    return empty($rows) ? FALSE : $rows[0];
  }

  public function fetchAssoc() {
    return empty($this->rows) ? FALSE : $this->rows[0];
  }

  public function fetchField($index = 0) {
    $column = $this->fetchCol($index);

    return empty($column) ? FALSE : $column[0];
  }

  public function rowCount() {
    return count($this->rows);
  }

  #[\ReturnTypeWillChange]
  public function count() {
    return count($this->rows);
  }

}

if (!function_exists('db_select')) {
  function db_select($table, $alias = NULL, array $options = []) {
    return new MyapiTestSelectQuery($table, $alias);
  }
}

/**
 * Replaces every fixture table and clears the recorded queries (SPEC 74).
 *
 * Called from setUp(), so no test inherits another's rows. Tables not named
 * here answer an empty result set, which is the same thing an empty table
 * answers in production.
 *
 * @param array $tables  Table name => list of rows (arrays or objects).
 */
function myapi_test_db_seed(array $tables = []) {
  $GLOBALS['myapi_test_db'] = $tables;
  $GLOBALS['myapi_test_db_queries'] = [];
}

/**
 * Every query executed since the last seed, in order, as recorded by
 * MyapiTestSelectQuery::execute().
 */
function myapi_test_db_queries($table = NULL) {
  $queries = isset($GLOBALS['myapi_test_db_queries']) ? $GLOBALS['myapi_test_db_queries'] : [];
  if ($table === NULL) {
    return $queries;
  }

  return array_values(array_filter($queries, function ($query) use ($table) {
    return $query['table'] === $table;
  }));
}

/**
 * The Field API, as a map of stored field definitions (SPEC 75).
 *
 * What makes myapi_update_7016() testable without a site. The update reads a
 * field definition, decides whether to write it back, and writes it — and the
 * three things SPEC 53 promises about it are all observable from that pair of
 * calls: that a second run writes nothing (idempotence), that what it writes
 * is a FIELD row and never a field_data_* one, and that a site missing one of
 * the fields runs it without error.
 *
 * field_read_field() is deliberately the stubbed one and not
 * field_info_field(): the update calls the former on purpose (see its own
 * docblock — the cached, processed definition carries a 'bundles' key that
 * must not be written back), and a stub of the other name would let that
 * distinction rot unnoticed.
 */
if (!defined('WATCHDOG_ERROR')) {
  define('WATCHDOG_ERROR', 3);
}
if (!defined('WATCHDOG_WARNING')) {
  define('WATCHDOG_WARNING', 4);
}
if (!defined('WATCHDOG_NOTICE')) {
  define('WATCHDOG_NOTICE', 5);
}

if (!function_exists('watchdog')) {
  function watchdog($type, $message, $variables = [], $severity = WATCHDOG_NOTICE, $link = NULL) {
    $GLOBALS['myapi_test_watchdog'][] = [
      'type'      => $type,
      'message'   => $message,
      'variables' => $variables,
      'severity'  => $severity,
      // The interpolated text, which is what a reader of the log actually
      // sees and therefore what a test asserting "it names the field" reads.
      'text'      => $variables ? strtr($message, $variables) : $message,
    ];
  }
}

if (!function_exists('field_read_field')) {
  /**
   * The stored definition, or FALSE for a field this site does not have —
   * which is exactly how Drupal answers for a field that was never created or
   * was deleted by hand.
   */
  function field_read_field($field_name, $include_additional = []) {
    return isset($GLOBALS['myapi_test_fields'][$field_name])
      ? $GLOBALS['myapi_test_fields'][$field_name]
      : FALSE;
  }
}

if (!function_exists('field_update_field')) {
  /**
   * Records the write AND applies it, so a second pass over the same fixture
   * reads what the first one left. Without applying it, an idempotence test
   * would be asserting against a map that never changed and would pass for
   * a function that writes unconditionally every time.
   */
  function field_update_field($field) {
    $GLOBALS['myapi_test_field_writes'][] = $field;
    $GLOBALS['myapi_test_fields'][$field['field_name']] = $field;

    return $field;
  }
}

if (!function_exists('field_info_cache_clear')) {
  function field_info_cache_clear() {
    $GLOBALS['myapi_test_field_cache_clears'] = ($GLOBALS['myapi_test_field_cache_clears'] ?? 0) + 1;
  }
}

/**
 * The write side of the database, recorded and never executed (SPEC 75).
 *
 * These exist to be asserted EMPTY. SPEC 53's fifth criterion is that the
 * update touches no field_data_* or field_revision_* row — a promise about
 * something that does NOT happen, which is unfalsifiable unless the forbidden
 * calls are observable. Any of them firing is recorded with its table name.
 */
function myapi_test_record_write($call, $table) {
  $GLOBALS['myapi_test_db_writes'][] = ['call' => $call, 'table' => $table];

  throw new RuntimeException($call . '(' . $table . ') is not available in tests/unit.');
}

if (!function_exists('db_insert')) {
  function db_insert($table, array $options = []) {
    myapi_test_record_write('db_insert', $table);
  }
}

if (!function_exists('db_update')) {
  function db_update($table, array $options = []) {
    myapi_test_record_write('db_update', $table);
  }
}

if (!function_exists('db_delete')) {
  function db_delete($table, array $options = []) {
    myapi_test_record_write('db_delete', $table);
  }
}

if (!function_exists('db_merge')) {
  function db_merge($table, array $options = []) {
    myapi_test_record_write('db_merge', $table);
  }
}

if (!function_exists('db_query')) {
  function db_query($query, array $args = [], array $options = []) {
    myapi_test_record_write('db_query', $query);
  }
}

if (!function_exists('user_load')) {
  /**
   * Answers an account out of $GLOBALS['myapi_test_users'] (SPEC 74).
   *
   * Faithful for the only two things myapi asks of it in a read path: whether
   * the account exists (FALSE when it does not, exactly as Drupal answers for
   * a deleted uid) and its 'status'. Nothing loads fields, roles or the
   * profile — a test that needs those builds them into the fixture account.
   */
  function user_load($uid, $reset = FALSE) {
    if (!isset($GLOBALS['myapi_test_users'][$uid])) {
      return FALSE;
    }

    return (object) $GLOBALS['myapi_test_users'][$uid];
  }
}

if (!function_exists('form_load_include')) {
  /**
   * The bookkeeping half of Drupal's own, which is the half that matters here:
   * the file is recorded in $form_state['build_info']['files'] so Drupal can
   * reload it when it retrieves a CACHED form — without it, a #submit handler
   * living in an .inc is an undefined function on POST. The loading half is
   * the module_load_include() stubbed above, i.e. a no-op out of Drupal.
   */
  function form_load_include(&$form_state, $type, $module, $name = NULL) {
    if (!isset($name)) {
      $name = $module;
    }
    if (!isset($form_state['build_info']['files']["$module:$name.$type"])) {
      $form_state['build_info']['files']["$module:$name.$type"] = array(
        'type' => $type,
        'module' => $module,
        'name' => $name,
      );

      return module_load_include($type, $module, $name);
    }

    return FALSE;
  }
}
