<?php

/**
 * @file
 * PHPUnit bootstrap for myapi unit tests.
 *
 * Lets tests `require` production .inc/.resource.inc files directly, outside
 * Drupal, with no copies. The only Drupal-level call these files make at file
 * scope (not inside a function) is module_load_include(), used by
 * resources/auth.resource.inc to pull in its includes/*.inc dependencies; this
 * stub makes that call a no-op so the require succeeds. Tests still `require`
 * the specific includes/*.inc files they actually exercise.
 *
 * If a future change adds another file-scope call to a Drupal function in one
 * of the .inc files exercised by tests/unit, this stub needs to grow to cover
 * it too — see tests/README.md.
 *
 * The four text helpers below (SPEC 50) are a different kind of stub: they are
 * called from INSIDE the functions under test, not at file scope, and each one
 * is a faithful one-line equivalent of the Drupal function for the only use
 * the tested code makes of it. They exist so the cancellation-reason texts can
 * be asserted character by character. Nothing here touches the database: the
 * suite still covers pure logic only.
 *
 * t() and form_set_error() (SPEC 52) are of that same kind, and are what makes
 * myapi_time_format_validate_fields() testable without a site: the walker is
 * shared by the 'area' and 'reservation' node forms, so one bug in it silences
 * the validation of four fields at once.
 *
 * drupal_get_path() and $base_url (SPEC 54) are the environment counterpart:
 * myapi_mail_logo_url() builds the header logo URL out of both, and every HTML
 * email template calls it, so without them the whole email suite fatals.
 *
 * element_children() (SPEC 59) is the same kind again: the only Drupal function
 * myapi_claim_transaction_transaction_form_alter() calls from inside, to walk
 * the langcode/delta levels of the field_claim widget.
 *
 * truncate_utf8() and drupal_substr() (SPEC 60) are what let the autogenerated
 * title of a 'claim_transaction' be asserted character by character: the title
 * cuts the operator's comment at 60 characters without breaking a word, and
 * that cut is core's, not myapi's.
 *
 * variable_get() and url() (SPEC 73) are the last of the Drupal kind: the reset
 * page reads its deep-link base out of a variable and builds its form action
 * with url(), and neither has any meaning outside a site.
 *
 * variable_get() and url() (SPEC 73) are the last of the Drupal kind: the reset
 * page reads its deep-link base out of a variable and builds its form action
 * with url(), and neither has any meaning outside a site.
 *
 * drupal_exit(), drupal_add_http_header() and drupal_json_encode() (SPEC 73)
 * are the three that opened the biggest door in this suite. Everything that
 * ANSWERS in this module — myapi_respond(), myapi_error(), and through them
 * every dispatcher and the password/reset page — ends by printing a body and
 * calling drupal_exit(). Stubbing that trio means the real helpers can run
 * here: the body goes to an output buffer, the status goes to a recorded
 * header, and the "and then the request ends" becomes a thrown MyapiExit.
 * myapi_test_capture() below is the only place that knows this, and no test
 * asserts against a reimplementation of the envelope — they assert against the
 * envelope production actually prints.
 *
 * ip_address() and the three Flood API functions (SPEC 73) are the same idea
 * for the brute-force helpers: myapi_flood_is_allowed() and
 * myapi_flood_register() are pure arithmetic over Drupal variables, and what is
 * worth testing about them is precisely the arguments they hand to
 * flood_is_allowed()/flood_register_event(). The stubs record every call so a
 * test can read them back.
 *
 * myapi_user_fetch_profile_fields() (SPEC 73) is the one stub in this file that
 * replaces a MYAPI function rather than a Drupal one: the real function is four
 * LEFT JOINs and belongs to tests/integration, while what SPEC 73 tests is its
 * consumer. SPEC 89 is what changed how it coexists with production. That same
 * .inc now also holds myapi_user_display_names(), which the suite DOES exercise
 * for real, so this file requires includes/myapi.user.inc — below the stub, and
 * the real profile-fields function carries a function_exists() guard so the
 * stub keeps winning. Nothing else in that file is stubbed.
 *
 * db_select(), user_load() and REQUEST_TIME (SPEC 74) are the newest kind and
 * the one that needs the loudest disclaimer. db_select() here is a FIXTURE
 * QUERY BUILDER, not a database: the rows a test seeds with
 * myapi_test_db_seed() are what execute() answers, after applying the
 * conditions and the ORDER BY over the columns the fixture carries and
 * projecting the fields/aliases the query asked for. What that makes testable
 * is the PHP half of a resource — the loops that turn rows into a response,
 * the delta precedence, the name fallbacks, the maps — running as production
 * runs it. What it does NOT do is execute SQL: joins are recorded, never
 * resolved (a joined column is seeded flat on the row, under the alias the
 * query gives it), and a condition on a column the fixture does not carry is
 * not applied. Everything SQL decides on its own — that a LEFT JOIN to a
 * multi-value field duplicates rows, that a real ORDER BY is what makes the
 * delta loop correct — stays tests/integration's job. Every query is recorded
 * in $GLOBALS['myapi_test_db_queries'] so a test can assert the SHAPE it built
 * (table, conditions, joins, order) where it cannot assert the SQL's outcome.
 *
 * taxonomy_vocabulary_machine_name_load() and taxonomy_get_tree() (SPEC 76) are
 * the same idea one level up: the banks resource does not query a table, it asks
 * the taxonomy API for a vocabulary and its tree. The stubs answer out of
 * fixtures seeded with myapi_test_taxonomy_seed() and record every call in
 * $GLOBALS['myapi_test_taxonomy_calls'], which is what lets a test assert both
 * the degraded path (no vocabulary -> FALSE, exactly as Drupal answers) and that
 * the tree was asked for the right vid — never that Drupal's own tree building
 * (hierarchy, weight order, access) is correct, which stays out of this layer.
 */

if (!function_exists('module_load_include')) {
  function module_load_include($type, $module, $name = NULL) {
    // No-op: unit tests require the relevant includes/*.inc files themselves.
  }
}

/**
 * The two halves of the logo URL myapi_mail_logo_url() assembles.
 *
 * Drupal resolves the path from the system table and $base_url from the
 * request; outside a site both are just constants, and the value only has to
 * be stable and plausible: no assertion reads the <img> src, it is the fatal
 * on the missing function that the tests need gone.
 */
if (!function_exists('drupal_get_path')) {
  function drupal_get_path($type, $name) {
    return 'sites/all/modules/' . $name;
  }
}

$GLOBALS['base_url'] = 'https://crespcord.example.com';

if (!function_exists('drupal_strlen')) {
  function drupal_strlen($text) {
    return mb_strlen($text, 'UTF-8');
  }
}

if (!function_exists('check_plain')) {
  function check_plain($text) {
    return htmlspecialchars($text, ENT_QUOTES, 'UTF-8');
  }
}

if (!function_exists('decode_entities')) {
  function decode_entities($text) {
    return html_entity_decode($text, ENT_QUOTES, 'UTF-8');
  }
}

if (!function_exists('format_date')) {
  /**
   * Only the 'custom' type is stubbed: it is the only one myapi calls, and it
   * maps straight onto date(). The site timezone is irrelevant here because
   * every fixture builds its timestamp with mktime() in the same one.
   */
  function format_date($timestamp, $type = 'medium', $format = '', $timezone = NULL, $langcode = NULL) {
    return date($format, $timestamp);
  }
}

if (!function_exists('drupal_substr')) {
  function drupal_substr($text, $start, $length = NULL) {
    return $length === NULL
      ? mb_substr($text, $start, NULL, 'UTF-8')
      : mb_substr($text, $start, $length, 'UTF-8');
  }
}

if (!function_exists('truncate_utf8')) {
  /**
   * Core's algorithm (includes/unicode.inc), reproduced (SPEC 60): the ellipsis
   * discounts its own character from the budget, $min_wordsafe_length bounds the
   * word-safe search, and a string with no boundary in range is cut hard.
   *
   * One declared divergence: core finds the cut with its own
   * PREG_CLASS_UNICODE_WORD_BOUNDARY character class, this uses '\s'. Every
   * fixture in ClaimTransactionTitleTest cuts on a plain space, where the two
   * agree; a fixture cutting on a hyphen or a comma would not, and that is why
   * none does.
   */
  function truncate_utf8($string, $max_length, $wordsafe = FALSE, $add_ellipsis = FALSE, $min_wordsafe_length = 1) {
    $ellipsis = '';
    $max_length = max($max_length, 0);
    $min_wordsafe_length = max($min_wordsafe_length, 0);

    if (drupal_strlen($string) <= $max_length) {
      return $string;
    }

    if ($add_ellipsis) {
      $ellipsis = drupal_substr('…', 0, $max_length);
      $max_length = max($max_length - drupal_strlen($ellipsis), 0);
    }

    if ($max_length <= $min_wordsafe_length) {
      $wordsafe = FALSE;
    }

    $matches = array();
    if ($wordsafe && preg_match('/^(.{' . $min_wordsafe_length . ',' . $max_length . '})\s/u', $string, $matches)) {
      $string = $matches[1];
    }
    else {
      $string = drupal_substr($string, 0, $max_length);
    }

    return $string . $ellipsis;
  }
}

if (!function_exists('t')) {
  /**
   * The placeholder substitution only: no string catalogue is involved outside
   * Drupal, and every myapi caller passes '@name' style placeholders, which
   * Drupal itself resolves with strtr() after check_plain(). Sanitisation is
   * left out on purpose — the tested code asserts the message text, and
   * escaping it here would only make the assertions harder to read.
   */
  function t($string, array $args = [], array $options = []) {
    return $args ? strtr($string, $args) : $string;
  }
}

if (!function_exists('form_set_error')) {
  /**
   * Records the error instead of touching a form: Drupal keeps these in a
   * static and prints them on the next page load, which is not observable from
   * a unit test. The recorded map is keyed by the element path exactly as the
   * production code builds it, so a test can assert WHICH input would be
   * flagged and not just how many errors came out.
   *
   * Tests reset $GLOBALS['myapi_test_form_errors'] in setUp(); the null
   * coalescing keeps a stray call outside a test from fataling.
   */
  function form_set_error($name = NULL, $message = '') {
    $GLOBALS['myapi_test_form_errors'] = $GLOBALS['myapi_test_form_errors'] ?? [];
    $GLOBALS['myapi_test_form_errors'][$name] = $message;
    return $GLOBALS['myapi_test_form_errors'];
  }
}

/**
 * form_error(), the element-level sibling of form_set_error() (SPEC 77).
 *
 * Drupal resolves the element's #parents into the same flat name
 * form_set_error() takes; here the element's own '#name' (or its first
 * #parents entry) is enough, because every caller in this module validates a
 * single top-level field. A test reads the errors back from
 * $GLOBALS['myapi_test_form_errors'], the same array form_set_error() writes.
 */
if (!function_exists('form_error')) {
  function form_error(&$element, $message = '') {
    $name = isset($element['#name'])
      ? $element['#name']
      : (isset($element['#parents'][0]) ? $element['#parents'][0] : 'element');

    return form_set_error($name, $message);
  }
}

if (!function_exists('element_children')) {
  /**
   * Every key that is not a '#property'. Drupal's own version also sorts by
   * '#weight' when asked; myapi never asks, and the widget's deltas are
   * already in order, so the sort is left out on purpose.
   *
   * The is_int() branch is the PHP 7.4 guard: field widget deltas are integer
   * keys, and $key[0] on an int raises "Trying to access array offset on value
   * of type int". An integer key is never a '#property', so short-circuiting
   * on it is faithful to the original rather than a deviation from it.
   */
  function element_children(&$elements, $sort = FALSE) {
    $children = array();
    foreach ($elements as $key => $value) {
      if (is_int($key) || $key === '' || $key[0] !== '#') {
        $children[] = $key;
      }
    }

    return $children;
  }
}

if (!function_exists('variable_get')) {
  /**
   * Reads from an in-memory map instead of the variables table (SPEC 73).
   *
   * Faithful for the only thing myapi asks of it: a site with no override
   * answers the default the call site passed, which is exactly what a test
   * asserting the shipped behaviour wants. A test that needs the overridden
   * branch sets $GLOBALS['myapi_test_variables'][$name] first and resets the
   * map in tearDown(), the same way a site administrator would set the
   * variable and the same way Drupal would then return it.
   */
  function variable_get($name, $default = NULL) {
    return isset($GLOBALS['myapi_test_variables'][$name])
      ? $GLOBALS['myapi_test_variables'][$name]
      : $default;
  }
}

if (!function_exists('url')) {
  /**
   * The root-relative half of Drupal's url() (SPEC 73).
   *
   * One declared divergence: path aliases are not resolved (myapi passes
   * system paths only). What IS faithful is the query string, which is the
   * part the tests assert — Drupal builds it with drupal_http_build_query(),
   * whose difference from http_build_query() is the encoding of the '/'
   * character, and no myapi query value contains one.
   *
   * 'absolute' was ignored until SPEC 77, when it stopped being unreachable:
   * every file URL the claims endpoint puts in a response is built with it,
   * and an app that received a root-relative one would request it against its
   * own host. It now prefixes $base_url, the same value Drupal would.
   */
  function url($path = NULL, array $options = []) {
    $url = '/' . ltrim((string) $path, '/');

    if (!empty($options['absolute'])) {
      $url = rtrim($GLOBALS['base_url'], '/') . $url;
    }

    if (!empty($options['query'])) {
      $url .= '?' . http_build_query($options['query']);
    }

    return $url;
  }
}

/**
 * The end of the request, as an exception (SPEC 73).
 *
 * drupal_exit() does not return, and neither does anything that calls it. The
 * throw is what reproduces that here: the code after a myapi_error() call
 * never runs in a test either, exactly as it never runs in production.
 */
class MyapiExit extends RuntimeException {
}

if (!function_exists('drupal_exit')) {
  function drupal_exit($destination = NULL) {
    throw new MyapiExit('drupal_exit()');
  }
}

if (!function_exists('drupal_add_http_header')) {
  /**
   * Records the header instead of sending it.
   *
   * Drupal keeps these in a static and flushes them with the response, which
   * is not observable from a unit test. The recorded map is what lets a test
   * assert the STATUS CODE of a response — 401 vs 422 vs 429 is half of this
   * API's contract, and asserting the body alone would miss it entirely.
   */
  function drupal_add_http_header($name, $value, $append = FALSE) {
    $GLOBALS['myapi_test_http_headers'][$name] = $value;
  }
}

if (!function_exists('drupal_json_encode')) {
  /**
   * Core's own (includes/common.inc), reproduced: json_encode() with the four
   * JSON_HEX_* flags that escape <, >, ' and & so a JSON response is safe to
   * embed in HTML.
   *
   * Faithful rather than convenient on purpose: the flags change the BYTES of
   * every response this module sends, and a test asserting a raw body would
   * silently disagree with production if this used a plain json_encode().
   */
  function drupal_json_encode($var) {
    return json_encode($var, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT);
  }
}

if (!function_exists('ip_address')) {
  function ip_address() {
    return isset($GLOBALS['myapi_test_ip']) ? $GLOBALS['myapi_test_ip'] : '203.0.113.7';
  }
}

if (!function_exists('flood_is_allowed')) {
  /**
   * Answers what the test told it to, and records how it was asked.
   *
   * The real one counts rows in the {flood} table, which is not what
   * myapi_flood_is_allowed() is responsible for. What IS its responsibility is
   * resolving a limit and a window out of two Drupal variable names and
   * passing them here in the right order — a threshold and a window swapped,
   * or a variable name misspelled, produces a silently wrong rate limit and no
   * error anywhere. Recording the arguments is what makes that assertable.
   */
  function flood_is_allowed($name, $threshold, $window = 3600, $identifier = NULL) {
    $GLOBALS['myapi_test_flood_calls'][] = [
      'call'       => 'is_allowed',
      'event'      => $name,
      'threshold'  => $threshold,
      'window'     => $window,
      'identifier' => $identifier,
    ];

    return isset($GLOBALS['myapi_test_flood_allowed']) ? $GLOBALS['myapi_test_flood_allowed'] : TRUE;
  }
}

if (!function_exists('flood_register_event')) {
  function flood_register_event($name, $window = 3600, $identifier = NULL) {
    $GLOBALS['myapi_test_flood_calls'][] = [
      'call'       => 'register',
      'event'      => $name,
      'window'     => $window,
      'identifier' => $identifier,
    ];
  }
}

if (!function_exists('flood_clear_event')) {
  function flood_clear_event($name, $identifier = NULL) {
    $GLOBALS['myapi_test_flood_calls'][] = [
      'call'       => 'clear',
      'event'      => $name,
      'identifier' => $identifier,
    ];
  }
}

/**
 * Runs a responder and returns everything it produced (SPEC 73).
 *
 * The single seam between "a function that answers and ends the request" and
 * an assertion. Every caller of myapi_respond()/myapi_error(), and every
 * render path of the password/reset page, goes through here.
 *
 * The output buffer is closed in a finally block: a callable that throws
 * something other than MyapiExit — a real bug in the code under test — must
 * not leave the buffer open and swallow the rest of the suite's output.
 *
 * @param callable $callable  The dispatcher, resource function or renderer.
 *
 * @return array  'exited'  — whether the request ended (it always should),
 *                'output'  — the raw printed body,
 *                'json'    — that body decoded, or NULL when it is not JSON,
 *                'status'  — the 'Status' header as an int, or NULL,
 *                'headers' — every header the call set.
 */
function myapi_test_capture(callable $callable) {
  $GLOBALS['myapi_test_http_headers'] = [];
  $exited = FALSE;

  ob_start();
  try {
    $callable();
  }
  catch (MyapiExit $e) {
    $exited = TRUE;
  }
  finally {
    $output = ob_get_clean();
  }

  $headers = $GLOBALS['myapi_test_http_headers'];

  return [
    'exited'  => $exited,
    'output'  => $output,
    'json'    => json_decode($output, TRUE),
    'status'  => isset($headers['Status']) ? (int) $headers['Status'] : NULL,
    'headers' => $headers,
  ];
}

if (!function_exists('myapi_user_fetch_profile_fields')) {
  /**
   * Returns a caller-provided profile row instead of running the field joins.
   *
   * The real function (includes/myapi.user.inc) is four LEFT JOINs over
   * field_data_field_nombre/apellidos/cedula/telefono; there is no way to
   * exercise it without a database, and no reason to, since what SPEC 73 tests
   * is its CONSUMER: myapi_auth_build_user_payload(), the "user" sub-object
   * that login and refresh both return and must never let drift apart.
   *
   * The default is the all-NULL row the real function answers for an account
   * with no profile values — the shape a test gets when it sets nothing.
   */
  function myapi_user_fetch_profile_fields($uid) {
    $default = ['first_name' => NULL, 'last_name' => NULL, 'dni' => NULL, 'phone' => NULL];

    return isset($GLOBALS['myapi_test_profile_fields'])
      ? $GLOBALS['myapi_test_profile_fields'] + $default
      : $default;
  }
}

/**
 * The real includes/myapi.user.inc, loaded after the stub above (SPEC 89).
 *
 * That file now holds two functions with opposite needs. The stub above must
 * keep winning for myapi_user_fetch_profile_fields(), whose five consumers'
 * tests seed $GLOBALS['myapi_test_profile_fields']; but
 * myapi_user_display_names() — the "nombre apellidos" / users.name rule SPEC 89
 * moved out of resources/unit.resource.inc — is real logic the suite exercises
 * through myapi_unit_fetch_user_names() and through the service request detail,
 * and it must be the production one, not a copy.
 *
 * Requiring the file here gives both: the stub is already declared, so the
 * function_exists() guard in the .inc skips the real profile-fields function,
 * and myapi_user_display_names() comes in for real. Order matters — this line
 * must stay BELOW the stub.
 */
require_once __DIR__ . '/../../includes/myapi.user.inc';

/**
 * The request timestamp (SPEC 74).
 *
 * Drupal defines it once per request in bootstrap.inc. Token expiry is compared
 * against it, so a fixture expressed as REQUEST_TIME +/- N seconds means the
 * same thing here as it does in production.
 */
if (!defined('REQUEST_TIME')) {
  define('REQUEST_TIME', time());
}

/**
 * A SELECT over fixtures (SPEC 74).
 *
 * Implements the subset of Drupal 7's SelectQuery that myapi's read paths
 * actually use: fields(), addField(), condition(), the join family, orderBy(),
 * range(), since SPEC 79 groupBy() and addExpression() as well, and since SPEC
 * 83 exists() with its correlated sub-select and the non-aggregate expressions
 * an ORDER BY reads, plus execute(). Anything else throws instead of returning
 * a wrong answer quietly
 * — a resource that starts using an unsupported clause must extend this class
 * knowingly, not discover that its test passed for the wrong reason. That is
 * how grouping got here: the category counter was written, the stub threw, and
 * the aggregation was implemented rather than mocked around.
 *
 * The rules, in full:
 *  - The base table names the fixture: myapi_test_db_seed(['node' => [...]])
 *    is what a SELECT ... FROM node reads.
 *  - Conditions are applied over the fixture's own columns, with the alias
 *    prefix stripped ('n.status' matches the 'status' key). A condition on a
 *    column the fixture row does not carry is skipped, which is what lets a
 *    test seed only the columns its case is about.
 *  - Joins are recorded, never resolved. A joined column is seeded flat on the
 *    row under the alias the query gives it ('area_m2', not
 *    'field_total_m2_value'), because that alias is what production reads off
 *    the result.
 *  - The projection is the field list: each requested field/alias is copied
 *    from the row when present and NULL otherwise, in the order it was added.
 *    fields($alias) with no column list selects the row whole, as in Drupal.
 */
class MyapiTestSelectQuery implements IteratorAggregate {

  private $table;
  private $alias;
  private $fields = [];
  private $select_all = FALSE;
  private $conditions = [];
  private $where = [];
  private $correlations = [];
  private $joins = [];
  private $order = [];
  private $range = NULL;
  private $count_mode = FALSE;
  private $group_by = [];
  private $expressions = [];
  private $tags = [];
  private $extenders = [];
  private $pager_limit = NULL;
  private $field_sources = [];

  public function __construct($table, $alias) {
    $this->table = $table;
    $this->alias = $alias;
  }

  public function fields($table_alias, array $fields = []) {
    if (empty($fields)) {
      $this->select_all = TRUE;
    }
    foreach ($fields as $field) {
      $this->fields[] = $field;
      $this->field_sources[$field] = $table_alias . '.' . $field;
    }

    return $this;
  }

  public function addField($table_alias, $field, $alias = NULL) {
    $alias = $alias !== NULL ? $alias : $field;
    $this->fields[] = $alias;
    $this->field_sources[$alias] = $table_alias . '.' . $field;

    return $this;
  }

  public function condition($field, $value = NULL, $operator = NULL) {
    // A condition GROUP — db_or() / db_and() (SPEC 77). The claims endpoint
    // builds its whole visibility rule as one: "public OR filed by the
    // reader". Recorded as a single condition whose 'group' carries the
    // sub-conditions, so a test can read the shape as well as the outcome.
    if ($field instanceof MyapiTestConditionGroup) {
      $this->conditions[] = ['field' => NULL, 'value' => NULL, 'operator' => 'GROUP', 'group' => $field];

      return $this;
    }
    if (!is_string($field)) {
      throw new RuntimeException('MyapiTestSelectQuery: only string conditions are supported.');
    }
    $this->conditions[] = [
      'field'    => $field,
      'value'    => $value,
      'operator' => $operator !== NULL ? strtoupper($operator) : (is_array($value) ? 'IN' : '='),
    ];

    return $this;
  }

  /**
   * A query tag, recorded and never applied (SPEC 77).
   *
   * ->addTag('node_access') is how the back-office claims listing delegates
   * its condominium scoping to hook_query_alter(); the alter itself is
   * Drupal's dispatch and cannot run here. Recording the tag is what lets a
   * test assert the delegation happened — losing that call is the difference
   * between "an administrador edificio sees their buildings" and "sees every
   * building of the site", and nothing else in the query would show it.
   */
  public function addTag($tag) {
    $this->tags[] = $tag;

    return $this;
  }

  public function hasTag($tag) {
    return in_array($tag, $this->tags, TRUE);
  }

  /**
   * PagerDefault, as far as this layer can go (SPEC 77).
   *
   * The real extender reads $_GET['page'], runs its own COUNT(*) and computes
   * an offset. Here it records the extender and answers the same object, so
   * ->limit() below can behave like the range it ultimately becomes. What is
   * NOT simulated is the page offset: every fixture pager answers the FIRST
   * page. A test about page 2 of the back-office listing belongs to
   * tests/integration, and no case here pretends otherwise.
   */
  public function extend($class) {
    $this->extenders[] = $class;

    return $this;
  }

  public function limit($limit = 10) {
    $this->pager_limit = $limit;

    return $this->range(0, $limit);
  }

  public function isNull($field) {
    $this->conditions[] = ['field' => $field, 'value' => NULL, 'operator' => 'IS NULL'];

    return $this;
  }

  public function isNotNull($field) {
    $this->conditions[] = ['field' => $field, 'value' => NULL, 'operator' => 'IS NOT NULL'];

    return $this;
  }

  /**
   * A raw SQL fragment, of the one shape myapi actually writes (SPEC 75).
   *
   * Every where() in this module is a date-range bound of the form
   *
   *   SUBSTR(alias.column, 1, 10) >= :date_from
   *
   * and that shape is parsed and APPLIED here rather than merely recorded,
   * because the date filter is half of what SPEC 15 promises keeps working
   * when pagination is switched off — a recorded-but-ignored bound would let
   * limit=-1 "return everything" past a filter that never ran.
   *
   * The SUBSTR is honoured literally (the stored value is a datetime and the
   * bound is a date, so the cut is what makes them comparable), and the
   * comparison reuses compare(), the same operator table the conditions use.
   *
   * Anything that is not that shape throws instead of being skipped quietly:
   * a resource that starts writing a different fragment must teach this parser
   * about it, not discover that its test passed because the bound evaporated.
   */
  public function where($snippet, array $arguments = []) {
    // The CORRELATION of an EXISTS sub-select — 'fc.entity_id = n.nid' (SPEC
    // 83, and the same shape SPEC 29 writes in the 'Personalizado' branch of
    // the bulletin visibility rule). Two column names and no placeholder: it
    // ties an inner row to the OUTER row being tested, so it is recorded apart
    // and applied by existsFor() below, never by matches().
    if (preg_match('/^([A-Za-z0-9_]+\.[A-Za-z0-9_]+)\s*=\s*([A-Za-z0-9_]+\.[A-Za-z0-9_]+)$/', trim($snippet), $c)) {
      $this->correlations[] = ['inner' => $c[1], 'outer' => $c[2]];

      return $this;
    }

    $pattern = '/^SUBSTR\(\s*([A-Za-z0-9_.]+)\s*,\s*1\s*,\s*(\d+)\s*\)\s*(>=|<=|<>|!=|=|<|>)\s*(:[A-Za-z0-9_]+)\s*$/';

    if (!preg_match($pattern, trim($snippet), $m)) {
      throw new RuntimeException('MyapiTestSelectQuery: unsupported where() fragment "' . $snippet . '".');
    }
    if (!array_key_exists($m[4], $arguments)) {
      throw new RuntimeException('MyapiTestSelectQuery: where() placeholder ' . $m[4] . ' has no argument.');
    }

    $this->where[] = [
      'snippet'   => $snippet,
      'arguments' => $arguments,
      'field'     => $m[1],
      'length'    => (int) $m[2],
      'operator'  => $m[3] === '!=' ? '<>' : $m[3],
      'value'     => $arguments[$m[4]],
    ];

    return $this;
  }

  /**
   * The row count of the same filtered set (SPEC 75).
   *
   * Drupal's countQuery() returns a NEW query that drops the field list, the
   * ordering and the range and answers a single COUNT(*) column; the clone
   * here does the same, which is what makes 'pagination.total' independent of
   * the page being fetched. Dropping the range is the part that matters: a
   * count that inherited it would answer the size of the page instead of the
   * size of the set, and every total_pages assertion would agree with itself
   * while being wrong.
   */
  public function countQuery() {
    $count = clone $this;
    $count->count_mode = TRUE;
    $count->fields = [];
    $count->select_all = FALSE;
    $count->order = [];
    $count->range = NULL;

    return $count;
  }

  /**
   * A correlated EXISTS sub-select, APPLIED and not merely recorded (SPEC 83).
   *
   * The marketplace listing filters by category with one of these, because
   * field_categories has unlimited cardinality and a JOIN would multiply rows.
   * A stub that recorded the sub-select and ignored it would answer the whole
   * marketplace to every ?category_id, and the filter tests would pass over a
   * filter that never ran — the exact failure the class docblock warns about.
   *
   * @param MyapiTestSelectQuery $select
   *   The sub-select, carrying its own conditions and its correlation to the
   *   outer row (see where() above).
   */
  public function exists($select) {
    if (!$select instanceof MyapiTestSelectQuery) {
      throw new RuntimeException('MyapiTestSelectQuery: exists() takes a fixture sub-select.');
    }
    $this->conditions[] = ['field' => NULL, 'value' => $select, 'operator' => 'EXISTS'];

    return $this;
  }

  /**
   * Whether this sub-select matches at least one row for the given outer row.
   *
   * Its own conditions first — over its own fixture table — and then every
   * correlation: the inner column must equal the outer one. Loose comparison,
   * like every other comparison here, because a fixture writes 41 where a
   * result set answers '41'.
   */
  public function existsFor(array $outer_row) {
    foreach ($this->matchedRows() as $inner_row) {
      $correlated = TRUE;
      foreach ($this->correlations as $correlation) {
        if ($this->value($inner_row, $correlation['inner']) != $this->value($outer_row, $correlation['outer'])) {
          $correlated = FALSE;
          break;
        }
      }
      if ($correlated) {
        return TRUE;
      }
    }

    return FALSE;
  }

  public function leftJoin($table, $alias = NULL, $condition = NULL) {
    return $this->addJoin('LEFT', $table, $alias, $condition);
  }

  public function innerJoin($table, $alias = NULL, $condition = NULL) {
    return $this->addJoin('INNER', $table, $alias, $condition);
  }

  public function join($table, $alias = NULL, $condition = NULL) {
    return $this->addJoin('INNER', $table, $alias, $condition);
  }

  private function addJoin($type, $table, $alias, $condition) {
    $this->joins[] = ['type' => $type, 'table' => $table, 'alias' => $alias, 'condition' => $condition];

    return $alias;
  }

  /**
   * GROUP BY, applied and not merely recorded (SPEC 79).
   *
   * The class docblock used to say a resource that started grouping had to
   * extend this builder knowingly; /api/v1/service-categories?with_counts=1 is
   * that resource, and this is that extension. It counts the active providers
   * of every category in ONE grouped query, so a stub that ignored the GROUP
   * BY would answer a single row and the whole point of the query — one count
   * per category — would go untested.
   *
   * Only the shape myapi writes is supported: grouping by real columns, with
   * the aggregate expressed through addExpression(). No HAVING.
   */
  public function groupBy($field) {
    $this->group_by[] = $field;

    return $this;
  }

  /**
   * An aggregate column (SPEC 79).
   *
   * Drupal answers the alias it assigned; so does this. The expression itself
   * is evaluated in aggregate() below, and only the two COUNT shapes this
   * module writes are understood — anything else throws rather than answering
   * a plausible wrong number.
   */
  public function addExpression($expression, $alias = NULL) {
    $alias = $alias !== NULL ? $alias : 'expression';
    $this->expressions[$alias] = $expression;
    $this->fields[] = $alias;

    return $alias;
  }

  public function orderBy($field, $direction = 'ASC') {
    $this->order[] = ['field' => $field, 'direction' => strtoupper($direction)];

    return $this;
  }

  public function range($start = NULL, $length = NULL) {
    $this->range = ['start' => (int) $start, 'length' => $length];

    return $this;
  }

  public function __call($name, $arguments) {
    throw new RuntimeException('MyapiTestSelectQuery: ' . $name . '() is not supported by the fixture query builder.');
  }

  #[\ReturnTypeWillChange]
  public function getIterator() {
    return new ArrayIterator($this->rows());
  }

  /**
   * Records the query and answers the fixture rows it selects.
   */
  public function execute() {
    $GLOBALS['myapi_test_db_queries'][] = [
      'table'      => $this->table,
      'alias'      => $this->alias,
      'fields'     => $this->fields,
      'select_all' => $this->select_all,
      'conditions' => $this->conditions,
      'where'      => $this->where,
      'joins'      => $this->joins,
      'order'      => $this->order,
      'range'      => $this->range,
      'count'      => $this->count_mode,
      'group_by'   => $this->group_by,
      'expressions' => $this->expressions,
      'tags'       => $this->tags,
      'extenders'  => $this->extenders,
    ];

    if ($this->count_mode) {
      // One row, one column, exactly as COUNT(*) answers — fetchField() reads
      // it positionally, so the column name is arbitrary.
      return new MyapiTestStatement([['expression' => count($this->matchedRows())]]);
    }

    return new MyapiTestStatement($this->rows());
  }

  /**
   * Filter, then order, then range, then project — the order a database
   * applies them in.
   */
  private function rows() {
    // A grouped query collapses before it is ordered or ranged, the way SQL
    // does it: aggregate first, then sort and slice the aggregated rows.
    if ($this->group_by || $this->hasAggregate()) {
      $rows = $this->sort($this->aggregate($this->matchedRows()));

      return $this->range !== NULL
        ? array_slice($rows, $this->range['start'], $this->range['length'])
        : $rows;
    }

    $rows = $this->matchedRows();

    // A NON-aggregate expression is a computed column of each row, and it is
    // computed BEFORE the sort because that is what the ORDER BY names: the
    // marketplace listing orders by '(column IS NULL)' to push the providers
    // with no rating or no rate to the end (SPEC 83). Computing it after
    // sorting would leave the ORDER BY reading a column that does not exist
    // yet, and the nulls would land wherever the fixture happened to sit.
    if ($this->expressions) {
      $rows = array_map([$this, 'computeExpressions'], $rows);
    }

    $rows = $this->sort($rows);

    if ($this->range !== NULL) {
      $rows = array_slice($rows, $this->range['start'], $this->range['length']);
    }

    return array_map([$this, 'project'], $rows);
  }

  /**
   * Collapses the matched rows into one row per GROUP BY value (SPEC 79).
   *
   * The fixture rows are the rows the JOINs would produce — one per
   * (provider, category) pair for the category counter — because joins are
   * recorded and never resolved here. Grouping them is therefore the same
   * arithmetic the database does over the same set.
   *
   * Groups come out in the order their first row appears in the fixture. Real
   * SQL guarantees no order without an ORDER BY, so no test should depend on
   * it; what it must not do is reorder rows behind a test's back, hence the
   * insertion order.
   */
  private function aggregate(array $rows) {
    $groups = [];
    foreach ($rows as $row) {
      $key = [];
      foreach ($this->group_by as $field) {
        $key[] = (string) $this->value($row, $field);
      }
      $groups[implode("\0", $key)][] = $row;
    }

    $aggregated = [];
    foreach ($groups as $group) {
      $projected = [];
      foreach ($this->fields as $field) {
        $projected[$field] = isset($this->expressions[$field])
          ? $this->evaluate($this->expressions[$field], $group)
          : $this->value($group[0], isset($this->field_sources[$field]) ? $this->field_sources[$field] : $field);
      }
      $aggregated[] = $projected;
    }

    return $aggregated;
  }

  /**
   * Whether any expression of this query is an aggregate (SPEC 83).
   *
   * The split that tells the two kinds of addExpression() apart: COUNT(...)
   * collapses rows and is answered by aggregate(), while '(x IS NULL)' is a
   * computed column of each row and is answered by computeExpressions(). Before
   * SPEC 83 every expression was an aggregate, so the presence of one was
   * enough to take the grouped path.
   */
  private function hasAggregate() {
    foreach ($this->expressions as $expression) {
      if (preg_match('/^\s*(COUNT|SUM|AVG|MIN|MAX)\s*\(/i', $expression)) {
        return TRUE;
      }
    }

    return FALSE;
  }

  /**
   * Adds the computed columns of one row, keyed by their alias (SPEC 83).
   */
  private function computeExpressions(array $row) {
    foreach ($this->expressions as $alias => $expression) {
      $row[$alias] = $this->evaluateRow($expression, $row);
    }

    return $row;
  }

  /**
   * Evaluates one non-aggregate expression over a single row (SPEC 83).
   *
   * Two shapes, which are the two this module writes:
   *
   *  - '(alias.column IS NULL)' — answers 1 or 0, the way SQL answers a
   *    boolean, so ORDER BY over it puts the rows WITH a value first.
   *  - a bare integer, which is the '1' of an EXISTS sub-select's select list.
   *
   * The column is resolved through the query's own alias map first: a fixture
   * row carries a joined column under the ALIAS the query gave it
   * ('rating_avg'), not under its qualified name — the rule stated in the class
   * docblock. Anything else throws rather than answering a plausible 0.
   */
  private function evaluateRow($expression, array $row) {
    $normalized = preg_replace('/\s+/', ' ', trim($expression));

    if (preg_match('/^\(?\s*([A-Za-z0-9_.]+)\s+IS NULL\s*\)?$/i', $normalized, $m)) {
      $alias = array_search($m[1], $this->field_sources, TRUE);
      $key = $alias !== FALSE ? $alias : $m[1];

      return $this->value($row, $key) === NULL ? 1 : 0;
    }

    if (preg_match('/^\d+$/', $normalized)) {
      return (int) $normalized;
    }

    throw new RuntimeException('MyapiTestSelectQuery: unsupported row expression "' . $expression . '".');
  }

  /**
   * Evaluates one aggregate expression over the rows of a group (SPEC 79).
   *
   * Understands COUNT(*), COUNT(alias.column) — which skips NULLs, as SQL
   * does — and COUNT(DISTINCT alias.column). Anything else throws: a stub that
   * guessed at SUM() or AVG() would answer a number that looks right and is
   * not, which is worse than not supporting it.
   */
  private function evaluate($expression, array $rows) {
    $normalized = preg_replace('/\s+/', ' ', trim($expression));

    if (preg_match('/^COUNT\(\s*\*\s*\)$/i', $normalized)) {
      return count($rows);
    }

    if (preg_match('/^COUNT\(\s*(DISTINCT\s+)?([A-Za-z0-9_.]+)\s*\)$/i', $normalized, $m)) {
      $values = [];
      foreach ($rows as $row) {
        $value = $this->value($row, $m[2]);
        if ($value !== NULL) {
          $values[] = $value;
        }
      }

      return $m[1] ? count(array_unique($values)) : count($values);
    }

    throw new RuntimeException('MyapiTestSelectQuery: unsupported expression "' . $expression . '".');
  }

  /**
   * Reads a column off a fixture row by its qualified name, its alias or its
   * bare column name (SPEC 79).
   *
   * The three-step fallback exists because a grouped query names the same
   * column three ways at once: the condition writes 'c.field_categories_tid',
   * the projection aliases it to 'tid', and the fixture row — which is the
   * joined row, written flat — carries plain 'field_categories_tid'. Used only
   * by the aggregation path, so the projection of every non-grouped query is
   * untouched.
   */
  private function value(array $row, $field) {
    if (array_key_exists($field, $row)) {
      return $row[$field];
    }

    $bare = $this->column($field);

    return array_key_exists($bare, $row) ? $row[$bare] : NULL;
  }

  /**
   * The fixture rows that survive the conditions and the where() fragments,
   * before any ordering, range or projection.
   */
  private function matchedRows() {
    $rows = isset($GLOBALS['myapi_test_db'][$this->table]) ? $GLOBALS['myapi_test_db'][$this->table] : [];
    $rows = array_map(function ($row) {
      return (array) $row;
    }, $rows);

    return array_values(array_filter($rows, [$this, 'matches']));
  }

  private function matches(array $row) {
    foreach ($this->conditions as $condition) {
      if ($condition['operator'] === 'EXISTS') {
        if (!$condition['value']->existsFor($row)) {
          return FALSE;
        }
        continue;
      }
      if ($condition['operator'] === 'GROUP') {
        if (!$this->matchesGroup($row, $condition['group'])) {
          return FALSE;
        }
        continue;
      }
      $column = $this->conditionKey($row, $condition['field']);
      if (!array_key_exists($column, $row)) {
        continue;
      }
      if (!$this->compare($row[$column], $condition['value'], $condition['operator'])) {
        return FALSE;
      }
    }

    foreach ($this->where as $fragment) {
      $column = $this->conditionKey($row, $fragment['field']);
      if (!array_key_exists($column, $row)) {
        continue;
      }
      // NULL is what a LEFT JOIN answers for a node with no row in the joined
      // field table, and SQL compares it to nothing: a bound always excludes
      // it, which is the documented behaviour of the date filter.
      if ($row[$column] === NULL) {
        return FALSE;
      }
      $actual = substr((string) $row[$column], 0, $fragment['length']);
      if (!$this->compare($actual, $fragment['value'], $fragment['operator'])) {
        return FALSE;
      }
    }

    return TRUE;
  }

  /**
   * Evaluates a db_or() / db_and() group over one fixture row (SPEC 77).
   *
   * Same laxness as the top-level conditions, applied one level down: a
   * sub-condition on a column the fixture does not carry is UNKNOWN and does
   * not participate. A group whose sub-conditions are all unknown is
   * satisfied, exactly as a single skipped condition is — which keeps a test
   * free to seed only the columns its case is about. With at least one known
   * sub-condition, OR needs one of them true and AND needs all of them.
   */
  private function matchesGroup(array $row, MyapiTestConditionGroup $group) {
    $known = 0;
    $true = 0;

    foreach ($group->conditions() as $condition) {
      $column = $this->conditionKey($row, $condition['field']);
      if (!array_key_exists($column, $row)) {
        continue;
      }
      $known++;
      if ($this->compare($row[$column], $condition['value'], $condition['operator'])) {
        $true++;
      }
    }

    if ($known === 0) {
      return TRUE;
    }

    return $group->conjunction() === 'OR' ? $true > 0 : $true === $known;
  }

  /**
   * Loose comparison on purpose: a real result set answers '1' where a fixture
   * writes 1, and no myapi condition depends on telling the two apart.
   */
  private function compare($actual, $expected, $operator) {
    switch ($operator) {
      case '=':
        return $actual == $expected;

      case '!=':
      case '<>':
        return $actual != $expected;

      case '>':
        return $actual > $expected;

      case '>=':
        return $actual >= $expected;

      case '<':
        return $actual < $expected;

      case '<=':
        return $actual <= $expected;

      case 'IN':
        return in_array($actual, (array) $expected);

      case 'NOT IN':
        return !in_array($actual, (array) $expected);

      case 'IS NULL':
        return $actual === NULL;

      case 'IS NOT NULL':
        return $actual !== NULL;
    }

    throw new RuntimeException('MyapiTestSelectQuery: unsupported operator "' . $operator . '".');
  }

  private function sort(array $rows) {
    foreach (array_reverse($this->order) as $order) {
      // Same qualified-then-bare resolution as the conditions (SPEC 77): the
      // ORDER BY of the claims fetch names the very column whose alias
      // collides with node.status, and a fixture that disambiguates it with
      // the qualified key must still sort by it.
      $column = $this->column($order['field']);
      // And, when no row carries the bare column, the ALIAS the query gave it
      // (SPEC 83): the listing orders by 'ra.field_rating_avg_value' while the
      // fixture row carries 'rating_avg', the alias of that very column. Only
      // as a fallback, so every query written before this stays sorted by
      // exactly the key it was sorted by.
      if (!$this->anyRowHas($rows, $column)) {
        $alias = array_search($order['field'], $this->field_sources, TRUE);
        if ($alias !== FALSE) {
          $column = $alias;
        }
      }
      foreach ($rows as $row) {
        if (array_key_exists($order['field'], $row)) {
          $column = $order['field'];
          break;
        }
      }
      $direction = $order['direction'] === 'DESC' ? -1 : 1;
      // usort() is not stable in PHP 7.4, so the original position is carried
      // as the tie-breaker: two rows with the same delta keep the order the
      // fixture wrote them in.
      $indexed = [];
      foreach ($rows as $position => $row) {
        $indexed[] = [$position, $row];
      }
      usort($indexed, function ($a, $b) use ($column, $direction) {
        $left = isset($a[1][$column]) ? $a[1][$column] : NULL;
        $right = isset($b[1][$column]) ? $b[1][$column] : NULL;
        if ($left == $right) {
          return $a[0] <=> $b[0];
        }

        return ($left < $right ? -1 : 1) * $direction;
      });
      $rows = array_column($indexed, 1);
    }

    return $rows;
  }

  private function project(array $row) {
    if ($this->select_all) {
      return $row;
    }

    $projected = [];
    foreach ($this->fields as $field) {
      // The QUALIFIED source first ('fs.field_status_value'), then the alias.
      // A fixture only needs the qualified form when an alias collides with a
      // real column of the base table — 'status' is projected off
      // field_data_field_status while n.status is the published flag, and a
      // flat row cannot hold both (SPEC 77).
      $source = isset($this->field_sources[$field]) ? $this->field_sources[$field] : NULL;

      if ($source !== NULL && array_key_exists($source, $row)) {
        $projected[$field] = $row[$source];
      }
      else {
        $projected[$field] = array_key_exists($field, $row) ? $row[$field] : NULL;
      }
    }

    return $projected;
  }

  /**
   * The fixture key a condition reads: the qualified name when the row carries
   * it, the bare column otherwise (SPEC 77 — same disambiguation as project()).
   */
  /**
   * Whether at least one of the rows carries this exact key (SPEC 83).
   */
  private function anyRowHas(array $rows, $key) {
    foreach ($rows as $row) {
      if (array_key_exists($key, $row)) {
        return TRUE;
      }
    }

    return FALSE;
  }

  private function conditionKey(array $row, $field) {
    return array_key_exists($field, $row) ? $field : $this->column($field);
  }

  private function column($field) {
    $position = strpos($field, '.');

    return $position === FALSE ? $field : substr($field, $position + 1);
  }

}

/**
 * The result of a fixture SELECT (SPEC 74).
 *
 * Answers the four fetchers myapi's read paths use, plus iteration, which is
 * how most of them consume a result. Rows come out as stdClass, exactly as
 * Drupal's default fetch mode delivers them.
 */
class MyapiTestStatement implements IteratorAggregate, Countable {

  private $rows;

  public function __construct(array $rows) {
    $this->rows = $rows;
  }

  #[\ReturnTypeWillChange]
  public function getIterator() {
    return new ArrayIterator($this->fetchAll());
  }

  public function fetchAll() {
    return array_map(function ($row) {
      return (object) $row;
    }, $this->rows);
  }

  public function fetchAllAssoc($key) {
    $result = [];
    foreach ($this->fetchAll() as $row) {
      $result[$row->{$key}] = $row;
    }

    return $result;
  }

  public function fetchCol($index = 0) {
    $column = [];
    foreach ($this->rows as $row) {
      $values = array_values($row);
      $column[] = isset($values[$index]) ? $values[$index] : NULL;
    }

    return $column;
  }

  public function fetchObject() {
    $rows = $this->fetchAll();

    return empty($rows) ? FALSE : $rows[0];
  }

  public function fetchAssoc() {
    return empty($this->rows) ? FALSE : $this->rows[0];
  }

  public function fetchField($index = 0) {
    $column = $this->fetchCol($index);

    return empty($column) ? FALSE : $column[0];
  }

  public function rowCount() {
    return count($this->rows);
  }

  #[\ReturnTypeWillChange]
  public function count() {
    return count($this->rows);
  }

}

/**
 * A db_or() / db_and() condition group (SPEC 77).
 *
 * Drupal's DatabaseCondition, reduced to what myapi builds with it: a
 * conjunction and a flat list of simple conditions. No nesting, because no
 * query in this module nests one — a group inside a group throws rather than
 * being silently flattened into the wrong boolean.
 */
class MyapiTestConditionGroup {

  private $conjunction;
  private $conditions = [];

  public function __construct($conjunction) {
    $this->conjunction = $conjunction;
  }

  public function condition($field, $value = NULL, $operator = NULL) {
    if (!is_string($field)) {
      throw new RuntimeException('MyapiTestConditionGroup: nested groups are not supported.');
    }
    $this->conditions[] = [
      'field'    => $field,
      'value'    => $value,
      'operator' => $operator !== NULL ? strtoupper($operator) : (is_array($value) ? 'IN' : '='),
    ];

    return $this;
  }

  public function isNull($field) {
    $this->conditions[] = ['field' => $field, 'value' => NULL, 'operator' => 'IS NULL'];

    return $this;
  }

  public function isNotNull($field) {
    $this->conditions[] = ['field' => $field, 'value' => NULL, 'operator' => 'IS NOT NULL'];

    return $this;
  }

  public function conjunction() {
    return $this->conjunction;
  }

  public function conditions() {
    return $this->conditions;
  }

}

if (!function_exists('db_or')) {
  function db_or() {
    return new MyapiTestConditionGroup('OR');
  }
}

if (!function_exists('db_and')) {
  function db_and() {
    return new MyapiTestConditionGroup('AND');
  }
}

if (!function_exists('db_select')) {
  function db_select($table, $alias = NULL, array $options = []) {
    return new MyapiTestSelectQuery($table, $alias);
  }
}

/**
 * Replaces every fixture table and clears the recorded queries (SPEC 74).
 *
 * Called from setUp(), so no test inherits another's rows. Tables not named
 * here answer an empty result set, which is the same thing an empty table
 * answers in production.
 *
 * @param array $tables  Table name => list of rows (arrays or objects).
 */
function myapi_test_db_seed(array $tables = []) {
  $GLOBALS['myapi_test_db'] = $tables;
  $GLOBALS['myapi_test_db_queries'] = [];
}

/**
 * Every query executed since the last seed, in order, as recorded by
 * MyapiTestSelectQuery::execute().
 */
function myapi_test_db_queries($table = NULL) {
  $queries = isset($GLOBALS['myapi_test_db_queries']) ? $GLOBALS['myapi_test_db_queries'] : [];
  if ($table === NULL) {
    return $queries;
  }

  return array_values(array_filter($queries, function ($query) use ($table) {
    return $query['table'] === $table;
  }));
}

/**
 * The Field API, as a map of stored field definitions (SPEC 75).
 *
 * What makes myapi_update_7016() testable without a site. The update reads a
 * field definition, decides whether to write it back, and writes it — and the
 * three things SPEC 53 promises about it are all observable from that pair of
 * calls: that a second run writes nothing (idempotence), that what it writes
 * is a FIELD row and never a field_data_* one, and that a site missing one of
 * the fields runs it without error.
 *
 * field_read_field() is deliberately the stubbed one and not
 * field_info_field(): the update calls the former on purpose (see its own
 * docblock — the cached, processed definition carries a 'bundles' key that
 * must not be written back), and a stub of the other name would let that
 * distinction rot unnoticed.
 */
if (!defined('WATCHDOG_ERROR')) {
  define('WATCHDOG_ERROR', 3);
}
if (!defined('WATCHDOG_WARNING')) {
  define('WATCHDOG_WARNING', 4);
}
if (!defined('WATCHDOG_NOTICE')) {
  define('WATCHDOG_NOTICE', 5);
}

if (!function_exists('watchdog')) {
  function watchdog($type, $message, $variables = [], $severity = WATCHDOG_NOTICE, $link = NULL) {
    $GLOBALS['myapi_test_watchdog'][] = [
      'type'      => $type,
      'message'   => $message,
      'variables' => $variables,
      'severity'  => $severity,
      // The interpolated text, which is what a reader of the log actually
      // sees and therefore what a test asserting "it names the field" reads.
      'text'      => $variables ? strtr($message, $variables) : $message,
    ];
  }
}

if (!function_exists('field_read_field')) {
  /**
   * The stored definition, or FALSE for a field this site does not have —
   * which is exactly how Drupal answers for a field that was never created or
   * was deleted by hand.
   */
  function field_read_field($field_name, $include_additional = []) {
    return isset($GLOBALS['myapi_test_fields'][$field_name])
      ? $GLOBALS['myapi_test_fields'][$field_name]
      : FALSE;
  }
}

if (!function_exists('field_update_field')) {
  /**
   * Records the write AND applies it, so a second pass over the same fixture
   * reads what the first one left. Without applying it, an idempotence test
   * would be asserting against a map that never changed and would pass for
   * a function that writes unconditionally every time.
   */
  function field_update_field($field) {
    $GLOBALS['myapi_test_field_writes'][] = $field;
    $GLOBALS['myapi_test_fields'][$field['field_name']] = $field;

    return $field;
  }
}

if (!function_exists('field_info_cache_clear')) {
  function field_info_cache_clear() {
    $GLOBALS['myapi_test_field_cache_clears'] = ($GLOBALS['myapi_test_field_cache_clears'] ?? 0) + 1;
  }
}

/**
 * The write side of the database, recorded and never executed (SPEC 75).
 *
 * These exist to be asserted EMPTY. SPEC 53's fifth criterion is that the
 * update touches no field_data_* or field_revision_* row — a promise about
 * something that does NOT happen, which is unfalsifiable unless the forbidden
 * calls are observable. Any of them firing is recorded with its table name.
 */
function myapi_test_record_write($call, $table) {
  $GLOBALS['myapi_test_db_writes'][] = ['call' => $call, 'table' => $table];

  throw new RuntimeException($call . '(' . $table . ') is not available in tests/unit.');
}

if (!function_exists('db_insert')) {
  function db_insert($table, array $options = []) {
    myapi_test_record_write('db_insert', $table);
  }
}

if (!function_exists('db_update')) {
  function db_update($table, array $options = []) {
    myapi_test_record_write('db_update', $table);
  }
}

if (!function_exists('db_delete')) {
  function db_delete($table, array $options = []) {
    myapi_test_record_write('db_delete', $table);
  }
}

if (!function_exists('db_merge')) {
  function db_merge($table, array $options = []) {
    myapi_test_record_write('db_merge', $table);
  }
}

if (!function_exists('db_query')) {
  function db_query($query, array $args = [], array $options = []) {
    myapi_test_record_write('db_query', $query);
  }
}

if (!function_exists('user_load')) {
  /**
   * Answers an account out of $GLOBALS['myapi_test_users'] (SPEC 74).
   *
   * Faithful for the only two things myapi asks of it in a read path: whether
   * the account exists (FALSE when it does not, exactly as Drupal answers for
   * a deleted uid) and its 'status'. Nothing loads fields, roles or the
   * profile — a test that needs those builds them into the fixture account.
   */
  function user_load($uid, $reset = FALSE) {
    if (!isset($GLOBALS['myapi_test_users'][$uid])) {
      return FALSE;
    }

    return (object) $GLOBALS['myapi_test_users'][$uid];
  }
}

if (!function_exists('form_load_include')) {
  /**
   * The bookkeeping half of Drupal's own, which is the half that matters here:
   * the file is recorded in $form_state['build_info']['files'] so Drupal can
   * reload it when it retrieves a CACHED form — without it, a #submit handler
   * living in an .inc is an undefined function on POST. The loading half is
   * the module_load_include() stubbed above, i.e. a no-op out of Drupal.
   */
  function form_load_include(&$form_state, $type, $module, $name = NULL) {
    if (!isset($name)) {
      $name = $module;
    }
    if (!isset($form_state['build_info']['files']["$module:$name.$type"])) {
      $form_state['build_info']['files']["$module:$name.$type"] = array(
        'type' => $type,
        'module' => $module,
        'name' => $name,
      );

      return module_load_include($type, $module, $name);
    }

    return FALSE;
  }
}

/**
 * The Field API, as read by the code under test (SPEC 77).
 *
 * field_info_field() answers the same $GLOBALS['myapi_test_fields'] map
 * field_read_field() already reads, so a fixture serves both; the difference
 * that matters to production — the cached definition carries 'bundles', the
 * stored one does not — is documented at field_read_field() above and no test
 * depends on it. FALSE for an unknown field is the whole point: it is how a
 * site missing 'field_status' or 'field_claim_type' answers, and the claims
 * code has an explicit branch for it in four places.
 */
if (!function_exists('field_info_field')) {
  function field_info_field($field_name) {
    return isset($GLOBALS['myapi_test_fields'][$field_name])
      ? $GLOBALS['myapi_test_fields'][$field_name]
      : NULL;
  }
}

if (!function_exists('field_info_instance')) {
  function field_info_instance($entity_type, $field_name, $bundle) {
    $key = $entity_type . ':' . $bundle . ':' . $field_name;

    return isset($GLOBALS['myapi_test_field_instances'][$key])
      ? $GLOBALS['myapi_test_field_instances'][$key]
      : NULL;
  }
}

/**
 * Seeds the allowed_values of a list field (SPEC 77).
 *
 * The one shape of field definition the claims code reads: every catalogue
 * check in the domain — the two back-office selects, the two write-path
 * validators — is a lookup into this array.
 *
 * @param array $fields  Field name => [stored value => label].
 */
function myapi_test_field_seed_allowed_values(array $fields = []) {
  $GLOBALS['myapi_test_fields'] = [];
  foreach ($fields as $field_name => $allowed_values) {
    $GLOBALS['myapi_test_fields'][$field_name] = [
      'field_name' => $field_name,
      'type'       => 'list_text',
      'settings'   => ['allowed_values' => $allowed_values],
    ];
  }
}

/**
 * Nodes and files, as fixtures (SPEC 77).
 *
 * node_load() and file_load() are the two loaders the claims code calls from
 * inside a decision — whether a transaction's claim exists, whether a file
 * still does, which condominium a claim belongs to — so they answer objects a
 * test seeded and FALSE for anything else, exactly as Drupal answers for a
 * deleted nid or fid. Nothing loads fields, revisions or access records: a
 * test that needs those builds them into the fixture object.
 */
function myapi_test_node_seed(array $nodes = []) {
  $GLOBALS['myapi_test_nodes'] = [];
  foreach ($nodes as $nid => $node) {
    $GLOBALS['myapi_test_nodes'][$nid] = is_object($node) ? $node : (object) $node;
  }
}

function myapi_test_file_seed(array $files = []) {
  $GLOBALS['myapi_test_files'] = [];
  foreach ($files as $fid => $file) {
    $GLOBALS['myapi_test_files'][$fid] = is_object($file) ? $file : (object) $file;
  }
}

/**
 * drupal_static(), as a resettable global (SPEC 77).
 *
 * The per-request memo Drupal gives a function that would otherwise repeat a
 * query. myapi uses it for the building admin's condominiums and for the
 * condominium of a node, both read several times per request. Faithful in the
 * one way that matters — it is a REFERENCE, so the caller's `$cache = &...`
 * writes back into it — and resettable between tests, which the real one is
 * not: without myapi_test_static_reset() in setUp() the second test of a class
 * would read the first one's fixture.
 */
if (!function_exists('drupal_static')) {
  function &drupal_static($name, $default_value = NULL, $reset = FALSE) {
    if (!isset($GLOBALS['myapi_test_statics'])) {
      $GLOBALS['myapi_test_statics'] = [];
    }
    if ($reset || !array_key_exists($name, $GLOBALS['myapi_test_statics'])) {
      $GLOBALS['myapi_test_statics'][$name] = $default_value;
    }

    return $GLOBALS['myapi_test_statics'][$name];
  }
}

function myapi_test_static_reset() {
  $GLOBALS['myapi_test_statics'] = [];
}

/**
 * The langcode key every field of this module is stored under (SPEC 77).
 */
if (!defined('LANGUAGE_NONE')) {
  define('LANGUAGE_NONE', 'und');
}

/**
 * node_save() and its two companions, as RECORDERS (SPEC 77).
 *
 * The loudest disclaimer of this file after db_select(): nothing here writes a
 * node. What they make testable is the ORCHESTRATION around the write — which
 * object the resource hands to node_save() after validating a request, in what
 * order the files are tied to it, and what the endpoint answers afterwards.
 * That object is the whole contract of myapi_claim_build_node(): field_requester
 * is the token's uid and never the request's, field_status is written
 * explicitly as 'received', and node.uid is the resident. A test can read all
 * three off $GLOBALS['myapi_test_node_saves'].
 *
 * What stays entirely with tests/integration: that node_save() persists, that
 * hook_node_insert() fires and creates the initial transaction, that
 * file_usage_add() protects a file from cron. A green test here says the
 * resource asked for the right thing, never that Drupal did it.
 *
 * The saved node gets the nid the test pre-assigned on the object, or the next
 * one from $GLOBALS['myapi_test_next_nid'] (900 by default), so the response
 * block that re-fetches the claim can be seeded in advance.
 */
if (!function_exists('node_object_prepare')) {
  function node_object_prepare(&$node) {
    $node->language = isset($node->language) ? $node->language : LANGUAGE_NONE;
    $node->status = isset($node->status) ? $node->status : 1;
    $node->promote = isset($node->promote) ? $node->promote : 0;
    $node->sticky = isset($node->sticky) ? $node->sticky : 0;
    $node->comment = isset($node->comment) ? $node->comment : 0;
    $node->is_new = empty($node->nid);
  }
}

if (!function_exists('node_save')) {
  function node_save($node) {
    if (empty($node->nid)) {
      $next = isset($GLOBALS['myapi_test_next_nid']) ? $GLOBALS['myapi_test_next_nid'] : 900;
      $node->nid = $next;
      $GLOBALS['myapi_test_next_nid'] = $next + 1;
    }
    $GLOBALS['myapi_test_node_saves'][] = $node;

    return $node;
  }
}

if (!function_exists('file_usage_add')) {
  function file_usage_add($file, $module, $type, $id, $count = 1) {
    $GLOBALS['myapi_test_file_usage'][] = ['op' => 'add', 'fid' => $file->fid, 'module' => $module, 'type' => $type, 'id' => $id];
  }
}

if (!function_exists('file_usage_delete')) {
  function file_usage_delete($file, $module, $type = NULL, $id = NULL, $count = 1) {
    $GLOBALS['myapi_test_file_usage'][] = ['op' => 'delete', 'fid' => $file->fid, 'module' => $module, 'type' => $type, 'id' => $id];
  }
}

if (!function_exists('file_delete')) {
  function file_delete($file, $force = FALSE) {
    $GLOBALS['myapi_test_file_deletes'][] = (int) $file->fid;

    return TRUE;
  }
}

/**
 * Everything the write paths recorded since the last reset (SPEC 77).
 */
function myapi_test_write_reset() {
  $GLOBALS['myapi_test_node_saves'] = [];
  $GLOBALS['myapi_test_file_usage'] = [];
  $GLOBALS['myapi_test_file_deletes'] = [];
  $GLOBALS['myapi_test_file_transfers'] = [];
  $GLOBALS['myapi_test_next_nid'] = 900;
}

function myapi_test_node_saves() {
  return isset($GLOBALS['myapi_test_node_saves']) ? $GLOBALS['myapi_test_node_saves'] : [];
}

function myapi_test_file_usage() {
  return isset($GLOBALS['myapi_test_file_usage']) ? $GLOBALS['myapi_test_file_usage'] : [];
}

function myapi_test_file_deletes() {
  return isset($GLOBALS['myapi_test_file_deletes']) ? $GLOBALS['myapi_test_file_deletes'] : [];
}

function myapi_test_file_transfers() {
  return isset($GLOBALS['myapi_test_file_transfers']) ? $GLOBALS['myapi_test_file_transfers'] : [];
}

if (!function_exists('node_load')) {
  function node_load($nid, $vid = NULL, $reset = FALSE) {
    return isset($GLOBALS['myapi_test_nodes'][(int) $nid])
      ? $GLOBALS['myapi_test_nodes'][(int) $nid]
      : FALSE;
  }
}

if (!function_exists('file_load')) {
  function file_load($fid) {
    return isset($GLOBALS['myapi_test_files'][(int) $fid])
      ? $GLOBALS['myapi_test_files'][(int) $fid]
      : FALSE;
  }
}

/**
 * node_access(), answered from a fixture (SPEC 77).
 *
 * The one Drupal decision the timeline's edit link defers to. A test sets
 * $GLOBALS['myapi_test_node_access'] as ['<op>:<nid>' => bool] for the
 * specific answers it cares about, and
 * $GLOBALS['myapi_test_node_access_default'] for the rest (TRUE when unset).
 * What this canNOT prove is Drupal's own resolution — the grants table, the
 * 'bypass node access' permission, the hook_node_access() of this module — so
 * no case here reads its result as "the building admin scoping works".
 */
if (!function_exists('node_access')) {
  function node_access($op, $node, $account = NULL) {
    $nid = is_object($node) && isset($node->nid) ? (int) $node->nid : $node;
    $key = $op . ':' . $nid;
    $GLOBALS['myapi_test_node_access_calls'][] = $key;

    if (isset($GLOBALS['myapi_test_node_access'][$key])) {
      return $GLOBALS['myapi_test_node_access'][$key];
    }

    return isset($GLOBALS['myapi_test_node_access_default'])
      ? $GLOBALS['myapi_test_node_access_default']
      : TRUE;
  }
}

/**
 * l(), reduced to the two things a test can read off it (SPEC 77): that the
 * text is escaped and that the path is the one the code built. The real
 * function resolves aliases, languages and attributes; none of that changes
 * which node a back-office cell points at.
 */
if (!function_exists('l')) {
  function l($text, $path, array $options = []) {
    return '<a href="/' . $path . '">' . check_plain($text) . '</a>';
  }
}

/**
 * file_transfer(), which ENDS the request (SPEC 77).
 *
 * The success path of GET /api/v1/claims/%/files/% — the one endpoint of the
 * module that answers bytes instead of the JSON envelope. The stub records the
 * uri and the headers and throws MyapiExit, the same way drupal_exit() does
 * for every other responder, so myapi_test_capture() sees a request that ended
 * and a test can assert the headers without streaming a file.
 */
if (!function_exists('file_transfer')) {
  function file_transfer($uri, $headers) {
    $GLOBALS['myapi_test_file_transfers'][] = ['uri' => $uri, 'headers' => $headers];

    throw new MyapiExit('file_transfer');
  }
}

/**
 * The taxonomy vocabularies and their terms, as fixtures (SPEC 76).
 *
 * Replaces both tables the banks resource reads through the taxonomy API and
 * clears the recorded calls. Called from setUp(), so no test inherits another's
 * vocabulary.
 *
 * @param array $vocabularies
 *   Machine name => list of term rows. Each row is an associative array that
 *   ends up as a term object; only 'tid', 'name' and 'description' matter to
 *   the resource, and a row may omit any of them to test the degraded shape.
 *   The list order is the order taxonomy_get_tree() answers in, i.e. Drupal's
 *   natural weight-then-name order, which is exactly what the resource then
 *   overrides.
 */
function myapi_test_taxonomy_seed(array $vocabularies = []) {
  $GLOBALS['myapi_test_vocabularies'] = [];
  $GLOBALS['myapi_test_taxonomy_terms'] = [];
  $GLOBALS['myapi_test_taxonomy_calls'] = [];
  // The hydrated terms of the entity_load() stub (SPEC 79) are cleared here
  // too, so a seed of any kind leaves no term of the previous test behind.
  $GLOBALS['myapi_test_taxonomy_entities'] = [];

  // vids are assigned in seeding order, starting at 1, the way a fresh site
  // hands them out. No test should depend on a particular number: the point of
  // the vid is that the resource carries the one it loaded into the tree call.
  $vid = 1;
  foreach ($vocabularies as $machine_name => $terms) {
    $GLOBALS['myapi_test_vocabularies'][$machine_name] = (object) [
      'vid'          => $vid,
      'machine_name' => $machine_name,
      'name'         => $machine_name,
    ];
    $GLOBALS['myapi_test_taxonomy_terms'][$vid] = array_map(function ($term) {
      return is_object($term) ? $term : (object) $term;
    }, $terms);
    $vid++;
  }
}

/**
 * Every taxonomy API call since the last seed, in order (SPEC 76).
 *
 * Each entry is ['function' => ..., 'args' => [...]].
 */
function myapi_test_taxonomy_calls() {
  return isset($GLOBALS['myapi_test_taxonomy_calls']) ? $GLOBALS['myapi_test_taxonomy_calls'] : [];
}

if (!function_exists('taxonomy_vocabulary_machine_name_load')) {
  /**
   * Answers a seeded vocabulary object, or FALSE (SPEC 76).
   *
   * FALSE for an unknown machine name is the whole reason this stub exists:
   * that is what Drupal answers for a renamed or deleted vocabulary, and the
   * `=== FALSE` branch of myapi_bank_list() is the endpoint's degraded path.
   */
  function taxonomy_vocabulary_machine_name_load($machine_name) {
    $GLOBALS['myapi_test_taxonomy_calls'][] = [
      'function' => 'taxonomy_vocabulary_machine_name_load',
      'args'     => [$machine_name],
    ];

    return isset($GLOBALS['myapi_test_vocabularies'][$machine_name])
      ? $GLOBALS['myapi_test_vocabularies'][$machine_name]
      : FALSE;
  }
}

if (!function_exists('taxonomy_get_tree')) {
  /**
   * Answers the seeded term list of a vid, in seeding order (SPEC 76).
   *
   * What it does NOT do is build a tree: hierarchy, depth, parents, the weight
   * ordering and term access are Drupal's, and no unit test can prove them. A
   * vid with no fixture answers an empty array, the same as an empty
   * vocabulary in production.
   */
  function taxonomy_get_tree($vid, $parent = 0, $max_depth = NULL, $load_entities = FALSE) {
    $GLOBALS['myapi_test_taxonomy_calls'][] = [
      'function' => 'taxonomy_get_tree',
      'args'     => [$vid, $parent, $max_depth, $load_entities],
    ];

    return isset($GLOBALS['myapi_test_taxonomy_terms'][$vid])
      ? $GLOBALS['myapi_test_taxonomy_terms'][$vid]
      : [];
  }
}

/* ---------------------------------------------------------------------------
 * The hydrated taxonomy terms and the public file URLs (SPEC 79).
 *
 * /api/v1/service-categories reads two Field API values off each term, and
 * taxonomy_get_tree() does not carry them: the resource loads the terms in a
 * second, batched call. These two stubs are what let that whole path run with
 * no site booted.
 * ------------------------------------------------------------------------ */

/**
 * Registers the hydrated version of the seeded terms (SPEC 79).
 *
 * Call it AFTER myapi_test_taxonomy_seed(), which clears this store. The rows
 * seeded into the tree are deliberately the light ones (no field values, as
 * taxonomy_get_tree() answers them), and the rows registered here are the full
 * ones: a resource that forgot to hydrate would therefore see no code and no
 * icon, which is exactly the production failure.
 *
 * @param array $terms
 *   List of term rows (or objects). Each one must carry a 'tid'.
 */
function myapi_test_taxonomy_entities_seed(array $terms) {
  $GLOBALS['myapi_test_taxonomy_entities'] = [];
  foreach ($terms as $term) {
    $term = is_object($term) ? $term : (object) $term;
    $GLOBALS['myapi_test_taxonomy_entities'][(string) $term->tid] = $term;
  }
}

if (!function_exists('entity_load')) {
  /**
   * Answers the hydrated terms of a list of tids, tid-keyed (SPEC 79).
   *
   * Faithful to Drupal in the two things the resource depends on: the answer
   * is an associative array KEYED BY id (which is why the resource has to
   * array_values() it before printing a JSON list), and a tid with no entity
   * is simply absent from the answer rather than present as NULL.
   *
   * A tid registered with myapi_test_taxonomy_entities_seed() answers that
   * object; otherwise the seeded tree term is answered, so a fixture that does
   * not care about field values can skip the second seed entirely.
   *
   * The call is recorded in myapi_test_taxonomy_calls(), which is what lets a
   * test prove the terms are loaded ONCE, in a single batch, and not one query
   * per term.
   */
  function entity_load($entity_type, $ids = FALSE, $conditions = [], $reset = FALSE) {
    $GLOBALS['myapi_test_taxonomy_calls'][] = [
      'function' => 'entity_load',
      'args'     => [$entity_type, $ids],
    ];

    if ($entity_type !== 'taxonomy_term' || !is_array($ids)) {
      return [];
    }

    // The tree store is the fallback, flattened by tid across vocabularies.
    $fallback = [];
    if (!empty($GLOBALS['myapi_test_taxonomy_terms'])) {
      foreach ($GLOBALS['myapi_test_taxonomy_terms'] as $terms) {
        foreach ($terms as $term) {
          if (isset($term->tid)) {
            $fallback[(string) $term->tid] = $term;
          }
        }
      }
    }

    $hydrated = isset($GLOBALS['myapi_test_taxonomy_entities'])
      ? $GLOBALS['myapi_test_taxonomy_entities']
      : [];

    $loaded = [];
    foreach ($ids as $id) {
      $key = (string) $id;
      if (isset($hydrated[$key])) {
        $loaded[(int) $id] = $hydrated[$key];
      }
      elseif (isset($fallback[$key])) {
        $loaded[(int) $id] = $fallback[$key];
      }
    }

    return $loaded;
  }
}

if (!function_exists('taxonomy_term_load')) {
  /**
   * Answers a single seeded term, hydrated with its OWN vid (SPEC 90).
   *
   * A real Drupal term object always carries its own `vid` — which vocabulary
   * it belongs to — and that is precisely the column
   * myapi_service_request_valid_category() compares against
   * taxonomy_vocabulary_machine_name_load()'s vid. myapi_test_taxonomy_seed()
   * stores the vid only on the vocabulary, keyed by it
   * ($GLOBALS['myapi_test_taxonomy_terms'][$vid]), so this stub is what stamps
   * it onto a COPY of the matching term before answering — never onto the
   * fixture itself, so a second load of the same tid is not corrupted by the
   * first.
   *
   * FALSE for an unknown tid, the same answer taxonomy_vocabulary_machine_name_
   * load() gives for an unknown machine name, and what
   * myapi_service_request_valid_category() reads as "not a real term".
   */
  function taxonomy_term_load($tid) {
    $GLOBALS['myapi_test_taxonomy_calls'][] = [
      'function' => 'taxonomy_term_load',
      'args'     => [$tid],
    ];

    $key = (string) $tid;

    if (!empty($GLOBALS['myapi_test_taxonomy_terms'])) {
      foreach ($GLOBALS['myapi_test_taxonomy_terms'] as $vid => $terms) {
        foreach ($terms as $term) {
          if (isset($term->tid) && (string) $term->tid === $key) {
            $hydrated = isset($GLOBALS['myapi_test_taxonomy_entities'][$key])
              ? clone $GLOBALS['myapi_test_taxonomy_entities'][$key]
              : clone $term;
            $hydrated->vid = $vid;

            return $hydrated;
          }
        }
      }
    }

    return FALSE;
  }
}

if (!function_exists('file_create_url')) {
  /**
   * Builds the absolute URL of a stored file URI (SPEC 79).
   *
   * Only the public:// scheme matters here — SPEC 77 created the category icon
   * field with uri_scheme = 'public', and the whole point of the icon being
   * public is that its URL works with no Drupal session. The mapping mirrors
   * the real one: public://x -> <base_url>/sites/default/files/x.
   *
   * The real function also handles private:// (a system/files route) and
   * external URLs; neither reaches this endpoint, so neither is stubbed.
   */
  function file_create_url($uri) {
    $public = 'public://';
    if (strpos($uri, $public) === 0) {
      return $GLOBALS['base_url'] . '/sites/default/files/' . substr($uri, strlen($public));
    }

    return $GLOBALS['base_url'] . '/' . ltrim($uri, '/');
  }
}
