<?php

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../../includes/myapi.request.inc';
require_once __DIR__ . '/../../includes/myapi.response.inc';
require_once __DIR__ . '/../../includes/myapi.i18n.inc';
require_once __DIR__ . '/../../includes/myapi.token.inc';
require_once __DIR__ . '/../../includes/myapi.auth.inc';
require_once __DIR__ . '/../../includes/myapi.unit_access.inc';
require_once __DIR__ . '/../../includes/myapi.reservation_query.inc';
require_once __DIR__ . '/../../resources/reservation.resource.inc';
require_once __DIR__ . '/../../includes/myapi.reservation_calendar.inc';
require_once __DIR__ . '/../../includes/myapi.claims_common.inc';
require_once __DIR__ . '/../../includes/myapi.claim_query.inc';
require_once __DIR__ . '/../../includes/myapi.claims_admin.inc';
require_once __DIR__ . '/../../includes/myapi.building_admin.inc';
require_once __DIR__ . '/../../includes/myapi.claim_transaction_admin.inc';
require_once __DIR__ . '/../../myapi.module';

/**
 * Unit tests for the back-office transactions timeline (SPECS 57/58/59,
 * covered by SPEC 77): the query, the two cell labels, the table body, the
 * whole block as the claim's edit form receives it, and the status-date
 * validator.
 *
 * The timeline is the operator's view of what happened to a claim and the
 * source of the status the resident reads in the app — a transaction that
 * sorts wrong, an author cell that fatals on a deleted account or a status
 * date accepted without a time are all failures the manual acceptance matrix
 * of those three specs checked once, by hand, in 2026.
 *
 * ClaimTransactionEditTest and ClaimTransactionTitleTest already cover the form
 * alter, the redirect handler and the autogenerated title. This class takes the
 * pieces they left out, including the two functions their own docblocks name as
 * out of reach — myapi_claim_transaction_edit_link() and the timeline rows —
 * which the SPEC 74/77 harness (fixture db_select(), node_load(), node_access())
 * makes reachable without changing a line of production.
 *
 * The disclaimer those docblocks made is still half true and worth repeating:
 * node_access() here is a FIXTURE, so a case that shows the edit link proves
 * "the link follows node_access()", never "the condominium scoping of an
 * administrador edificio works". That second question is Drupal's grants
 * system and stays with tests/integration.
 */
class ClaimTimelineTest extends TestCase {

  protected function setUp(): void {
    myapi_test_db_seed();
    myapi_test_node_seed();
    myapi_test_static_reset();
    myapi_test_field_seed_allowed_values([
      'field_status' => [
        'received'    => 'Recibido',
        'in_progress' => 'En proceso',
        'resolved'    => 'Resuelto',
        'closed'      => 'Cerrado',
      ],
    ]);
    $GLOBALS['myapi_test_node_access'] = [];
    $GLOBALS['myapi_test_node_access_default'] = TRUE;
    $GLOBALS['myapi_test_node_access_calls'] = [];
    $GLOBALS['myapi_test_form_errors'] = [];
  }

  protected function tearDown(): void {
    myapi_test_db_seed();
    myapi_test_node_seed();
    myapi_test_static_reset();
    $GLOBALS['myapi_test_fields'] = [];
    unset($GLOBALS['myapi_test_node_access'], $GLOBALS['myapi_test_node_access_default']);
    $GLOBALS['myapi_test_form_errors'] = [];
  }

  /**
   * A published transaction of claim 140, with every column the timeline reads.
   *
   * 'fs.field_status_value' is qualified because the alias 'status' the query
   * projects collides with node.status, the published flag.
   */
  private function transaction(array $overrides = []) {
    return $overrides + [
      'nid'     => 15,
      'type'    => 'claim_transaction',
      'status'  => 1,
      'uid'     => 41,
      'created' => mktime(9, 35, 0, 8, 5, 2026),
      'field_claim_target_id' => 140,
      'fs.field_status_value' => 'in_progress',
      'fsd.field_status_date_value' => '2026-08-05 09:30:00',
      'comment'   => 'Se coordinó la visita',
      'user_name' => 'operador',
    ];
  }

  /* -------------------------------------------------------------------------
   * myapi_claim_transaction_timeline_rows().
   * ---------------------------------------------------------------------- */

  /**
   * One row per published transaction of THIS claim, with the seven columns
   * the table reads.
   */
  public function testTheRowsCarryEveryColumnTheTableNeeds() {
    myapi_test_db_seed(['node' => [$this->transaction()]]);

    $rows = myapi_claim_transaction_timeline_rows(140);

    $this->assertCount(1, $rows);
    $this->assertSame(15, (int) $rows[0]->nid);
    $this->assertSame(41, (int) $rows[0]->uid);
    $this->assertSame('in_progress', $rows[0]->status);
    $this->assertSame('2026-08-05 09:30:00', $rows[0]->status_date);
    $this->assertSame('Se coordinó la visita', $rows[0]->comment);
    $this->assertSame('operador', $rows[0]->user_name);
  }

  /**
   * The full stored instant travels, not just its date part: SPEC 58 widened
   * field_status_date to minutes and dropped the SUBSTR that used to cut it.
   */
  public function testTheStatusDateKeepsItsTime() {
    myapi_test_db_seed(['node' => [$this->transaction()]]);

    $rows = myapi_claim_transaction_timeline_rows(140);

    $this->assertStringContainsString('09:30', $rows[0]->status_date);
  }

  /**
   * Newest first, tie-broken by nid descending — the order that makes the
   * table deterministic when two transactions share an instant.
   */
  public function testTheTimelineIsNewestFirstAndTieBrokenByNid() {
    $same_instant = '2026-08-05 09:30:00';
    myapi_test_db_seed(['node' => [
      $this->transaction(['nid' => 12, 'fsd.field_status_date_value' => '2026-08-04 16:46:00']),
      $this->transaction(['nid' => 15, 'fsd.field_status_date_value' => $same_instant]),
      $this->transaction(['nid' => 18, 'fsd.field_status_date_value' => $same_instant]),
    ]]);

    $rows = myapi_claim_transaction_timeline_rows(140);

    $this->assertSame([18, 15, 12], array_map('intval', array_column($rows, 'nid')));
  }

  /**
   * Only this claim's transactions, only published ones, only that bundle.
   */
  public function testForeignUnpublishedAndOtherBundleRowsAreExcluded() {
    myapi_test_db_seed(['node' => [
      $this->transaction(['nid' => 15]),
      $this->transaction(['nid' => 16, 'field_claim_target_id' => 999]),
      $this->transaction(['nid' => 17, 'status' => 0]),
      $this->transaction(['nid' => 18, 'type' => 'reclamo']),
    ]]);

    $rows = myapi_claim_transaction_timeline_rows(140);

    $this->assertSame([15], array_map('intval', array_column($rows, 'nid')));
  }

  /**
   * A transaction missing its status, its date or its comment still appears —
   * LEFT and not INNER, so a half-filled row is visible to the operator who
   * has to fix it rather than silently absent.
   */
  public function testAHalfFilledTransactionStillAppears() {
    myapi_test_db_seed(['node' => [$this->transaction([
      'fs.field_status_value' => NULL,
      'fsd.field_status_date_value' => NULL,
      'comment' => NULL,
      'user_name' => NULL,
    ])]]);

    $rows = myapi_claim_transaction_timeline_rows(140);

    $this->assertCount(1, $rows);
    $this->assertNull($rows[0]->status);
    $this->assertNull($rows[0]->status_date);
  }

  /**
   * A claim with no transactions answers an empty list, not an error.
   */
  public function testAClaimWithNoTransactionsAnswersAnEmptyList() {
    myapi_test_db_seed(['node' => []]);

    $this->assertSame([], myapi_claim_transaction_timeline_rows(140));
  }

  /* -------------------------------------------------------------------------
   * myapi_claim_transaction_author_label().
   * ---------------------------------------------------------------------- */

  /**
   * Two cases only: the account is there, or it was deleted since. node.uid is
   * never NULL, so there is no "nobody set" case as in the claims listing.
   */
  public function testTheAuthorLabelHasTwoCases() {
    $present = (object) ['uid' => 41, 'user_name' => 'operador'];
    $deleted = (object) ['uid' => 41, 'user_name' => NULL];

    $this->assertSame('operador', myapi_claim_transaction_author_label($present));
    $this->assertSame('Usuario eliminado (#41)', myapi_claim_transaction_author_label($deleted));
  }

  /**
   * The username is escaped: it is printed into an HTML table.
   */
  public function testTheAuthorNameIsEscaped() {
    $row = (object) ['uid' => 41, 'user_name' => '<b>op</b>'];

    $this->assertSame('&lt;b&gt;op&lt;/b&gt;', myapi_claim_transaction_author_label($row));
  }

  /* -------------------------------------------------------------------------
   * myapi_claim_transaction_edit_link().
   * ---------------------------------------------------------------------- */

  /**
   * The link points at the transaction's own edit form.
   */
  public function testTheEditLinkPointsAtTheTransaction() {
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);

    $this->assertSame('<a href="/node/15/edit">Editar</a>', myapi_claim_transaction_edit_link(15));
  }

  /**
   * It is HIDDEN and not disabled for a user who may not update the node: a
   * link that leads to a 403 is worse than no link. Empty string, no
   * substitute text.
   */
  public function testTheEditLinkIsEmptyWithoutUpdateAccess() {
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);
    $GLOBALS['myapi_test_node_access']['update:15'] = FALSE;

    $this->assertSame('', myapi_claim_transaction_edit_link(15));
  }

  /**
   * A transaction that no longer loads gets no link either, and node_access()
   * is never asked about a FALSE node.
   */
  public function testAMissingTransactionGetsNoLink() {
    myapi_test_node_seed();
    $GLOBALS['myapi_test_node_access_calls'] = [];

    $this->assertSame('', myapi_claim_transaction_edit_link(15));
    $this->assertSame([], $GLOBALS['myapi_test_node_access_calls']);
  }

  /**
   * The decision is delegated to node_access('update', ...) — not reimplemented
   * — which is what makes it inherit the per-condominium rule of SPEC 56
   * instead of drifting from it.
   */
  public function testTheEditLinkAsksNodeAccessForUpdate() {
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);

    myapi_claim_transaction_edit_link(15);

    $this->assertSame(['update:15'], $GLOBALS['myapi_test_node_access_calls']);
  }

  /* -------------------------------------------------------------------------
   * myapi_claim_transaction_timeline_table_rows().
   * ---------------------------------------------------------------------- */

  private function row(array $overrides = []) {
    return (object) ($overrides + [
      'nid'         => 15,
      'uid'         => 41,
      'status'      => 'in_progress',
      'status_date' => '2026-08-05 09:30:00',
      'comment'     => 'Se coordinó la visita',
      'user_name'   => 'operador',
    ]);
  }

  /**
   * The five cells of a timeline row.
   */
  public function testARowBecomesTheFiveDocumentedCells() {
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);

    $rows = myapi_claim_transaction_timeline_table_rows([$this->row()]);

    $this->assertCount(1, $rows);
    $this->assertSame('En proceso', $rows[0][0]);
    $this->assertSame('05/08/2026 09:30', $rows[0][1]);
    $this->assertSame('Se coordinó la visita', $rows[0][2]);
    $this->assertSame('operador', $rows[0][3]);
    $this->assertSame(['data' => ['#markup' => '<a href="/node/15/edit">Editar</a>']], $rows[0][4]);
  }

  /**
   * The edit cell is a '#markup' RENDER ELEMENT and not a plain string:
   * theme_table() runs check_plain() over a string cell, which would print the
   * <a> tag instead of the link.
   */
  public function testTheEditCellIsARenderElementAndNotAString() {
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);

    $rows = myapi_claim_transaction_timeline_table_rows([$this->row()]);

    $this->assertIsArray($rows[0][4]);
    $this->assertArrayHasKey('#markup', $rows[0][4]['data']);
  }

  /**
   * A missing status date and an empty comment print an em dash instead of an
   * empty cell — and a transaction stored before SPEC 58 shows its '00:00'.
   */
  public function testMissingValuesPrintAnEmDash() {
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);

    $rows = myapi_claim_transaction_timeline_table_rows([
      $this->row(['status_date' => NULL, 'comment' => NULL]),
      $this->row(['nid' => 16, 'comment' => '', 'status_date' => '2026-01-05 00:00:00']),
    ]);

    $this->assertSame('—', $rows[0][1]);
    $this->assertSame('—', $rows[0][2]);
    $this->assertSame('05/01/2026 00:00', $rows[1][1]);
    $this->assertSame('—', $rows[1][2]);
  }

  /**
   * The comment is escaped: an operator types it into a textarea and the table
   * renders it as HTML.
   */
  public function testTheCommentIsEscaped() {
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);

    $rows = myapi_claim_transaction_timeline_table_rows([
      $this->row(['comment' => '<script>alert(1)</script>']),
    ]);

    $this->assertSame('&lt;script&gt;alert(1)&lt;/script&gt;', $rows[0][2]);
  }

  /**
   * An unknown status prints the raw stored value rather than a blank cell.
   */
  public function testAnUnknownStatusPrintsItsRawValue() {
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);

    $rows = myapi_claim_transaction_timeline_table_rows([$this->row(['status' => 'duplicated'])]);

    $this->assertSame('duplicated', $rows[0][0]);
  }

  /* -------------------------------------------------------------------------
   * myapi_claim_transaction_timeline_build() and the 'reclamo' form alter.
   * ---------------------------------------------------------------------- */

  /**
   * The block is the creation link FIRST and then the table — the order SPEC 57
   * states in its acceptance criteria.
   */
  public function testTheBlockPutsTheCreationLinkBeforeTheTable() {
    myapi_test_db_seed(['node' => [$this->transaction()]]);
    myapi_test_node_seed([15 => ['nid' => 15, 'type' => 'claim_transaction']]);

    $build = myapi_claim_transaction_timeline_build((object) ['nid' => 140, 'type' => 'reclamo']);

    $this->assertSame(['create_link', 'table'], array_keys($build));
    $this->assertStringContainsString('node/140/claim-transaction/add', $build['create_link']['#markup']);
    $this->assertSame('table', $build['table']['#theme']);
    $this->assertCount(1, $build['table']['#rows']);
  }

  /**
   * A claim with no transactions still renders the table, with its own empty
   * text instead of nothing at all.
   */
  public function testAnEmptyTimelineCarriesItsEmptyText() {
    myapi_test_db_seed(['node' => []]);

    $build = myapi_claim_transaction_timeline_build((object) ['nid' => 140]);

    $this->assertSame([], $build['table']['#rows']);
    $this->assertSame('Todavía no hay transacciones para este reclamo.', $build['table']['#empty']);
  }

  /**
   * On the claim's EDIT form, field_status is disabled — the status is moved by
   * creating a transaction, never by typing it here — and the timeline is
   * appended as a fieldset at the bottom.
   *
   * #disabled and not #access = FALSE on purpose: Drupal resubmits a disabled
   * element's default value, so saving the rest of the form never blanks the
   * field.
   */
  public function testTheClaimEditFormDisablesTheStatusAndAppendsTheTimeline() {
    myapi_test_db_seed(['node' => []]);
    $form = [
      '#node' => (object) ['nid' => 140, 'type' => 'reclamo'],
      'field_status' => [
        LANGUAGE_NONE => ['#type' => 'select'],
        'es' => ['#type' => 'select'],
        '#tree' => TRUE,
      ],
    ];
    $form_state = [];

    myapi_claim_transaction_reclamo_form_alter($form, $form_state);

    $this->assertTrue($form['field_status'][LANGUAGE_NONE]['#disabled']);
    $this->assertTrue($form['field_status']['es']['#disabled'], 'every language, not only the first');
    $this->assertSame('fieldset', $form['myapi_claim_transactions']['#type']);
    $this->assertArrayHasKey('table', $form['myapi_claim_transactions']);
  }

  /**
   * On node/add/reclamo nothing is touched: the newly created claim's
   * field_status is what the automatic initial transaction copies, so it stays
   * editable there. Deliberate, per SPEC 57's decisions.
   */
  public function testTheClaimCreationFormIsLeftAlone() {
    $form = [
      '#node' => (object) ['type' => 'reclamo'],
      'field_status' => [LANGUAGE_NONE => ['#type' => 'select']],
    ];
    $form_state = [];

    myapi_claim_transaction_reclamo_form_alter($form, $form_state);

    $this->assertArrayNotHasKey('#disabled', $form['field_status'][LANGUAGE_NONE]);
    $this->assertArrayNotHasKey('myapi_claim_transactions', $form);
  }

  /* -------------------------------------------------------------------------
   * myapi_claim_transaction_validate_status_date().
   * ---------------------------------------------------------------------- */

  private function validate($value) {
    $element = ['#value' => $value, '#name' => 'status_date'];
    $form_state = [];
    myapi_claim_transaction_validate_status_date($element, $form_state);

    return $GLOBALS['myapi_test_form_errors'];
  }

  /**
   * A full instant passes.
   */
  public function testAValidDateAndTimePasses() {
    $this->assertSame([], $this->validate('2026-08-05 09:30'));
    $this->assertSame([], $this->validate('  2026-08-05 09:30  '), 'trimmed first');
  }

  /**
   * A bare DATE fails: SPEC 58 requires the exact instant of the status
   * change, so a value with no time part is not accepted.
   */
  public function testABareDateIsRejected() {
    $errors = $this->validate('2026-08-05');

    $this->assertArrayHasKey('status_date', $errors);
    $this->assertStringContainsString('AAAA-MM-DD HH:MM', $errors['status_date']);
  }

  /**
   * An impossible calendar date and an impossible clock time are both
   * rejected, which a format-only check would let through.
   */
  public function testImpossibleDatesAndTimesAreRejected() {
    foreach (['2026-02-30 09:30', '2026-08-05 25:00', '2026-08-05 09:70', '05/08/2026 09:30', '', 'ayer'] as $value) {
      $GLOBALS['myapi_test_form_errors'] = [];

      $this->assertArrayHasKey('status_date', $this->validate($value), var_export($value, TRUE));
    }
  }

  /* -------------------------------------------------------------------------
   * The access callback of the creation route (SPEC 57).
   * ---------------------------------------------------------------------- */

  /**
   * The route is node/%node/claim-transaction/add for ANY node id, so
   * everything that is not a 'reclamo' is closed — including a
   * 'claim_transaction' itself.
   */
  public function testTheCreationRouteIsClosedForEveryOtherBundle() {
    foreach (['boletin', 'claim_transaction', 'vivienda'] as $type) {
      $this->assertFalse(myapi_claim_transaction_add_access((object) ['nid' => 5, 'type' => $type]), $type);
    }

    $this->assertFalse(myapi_claim_transaction_add_access(NULL));
    $this->assertFalse(myapi_claim_transaction_add_access('reclamo'));
  }

  /**
   * For a 'reclamo' it defers entirely to node_access(), and needs BOTH
   * permissions: updating the claim and creating a transaction. Either one
   * missing closes the route.
   */
  public function testTheCreationRouteNeedsBothUpdateAndCreate() {
    $claim = (object) ['nid' => 140, 'type' => 'reclamo'];

    $GLOBALS['myapi_test_node_access'] = [];
    $this->assertTrue(myapi_claim_transaction_add_access($claim));

    $GLOBALS['myapi_test_node_access'] = ['update:140' => FALSE];
    $this->assertFalse(myapi_claim_transaction_add_access($claim));

    $GLOBALS['myapi_test_node_access'] = ['create:claim_transaction' => FALSE];
    $this->assertFalse(myapi_claim_transaction_add_access($claim));
  }

  /* -------------------------------------------------------------------------
   * myapi_claim_transaction_title_comment() — the cut SPEC 60 reuses.
   * ---------------------------------------------------------------------- */

  /**
   * Newlines and runs of whitespace collapse to single spaces, so a comment
   * typed across three lines does not put line breaks in node.title.
   */
  public function testTheTitleCommentCollapsesWhitespace() {
    $this->assertSame(
      'Se coordinó la visita con el plomero',
      myapi_claim_transaction_title_comment("Se coordinó   la visita\n\ncon el plomero")
    );
  }

  /**
   * An empty or whitespace-only comment answers '' so the segment is dropped
   * from the title instead of leaving a dangling separator.
   */
  public function testAnEmptyTitleCommentIsAnEmptyString() {
    $this->assertSame('', myapi_claim_transaction_title_comment(NULL));
    $this->assertSame('', myapi_claim_transaction_title_comment(''));
    $this->assertSame('', myapi_claim_transaction_title_comment("   \n\t "));
  }

  /**
   * A long comment is cut on a word boundary and ends in an ellipsis — the cut
   * is core's truncate_utf8(), not a hand-rolled substr().
   */
  public function testALongTitleCommentIsCutOnAWordBoundary() {
    $comment = str_repeat('palabra ', 20);

    $cut = myapi_claim_transaction_title_comment($comment);

    $this->assertStringEndsWith('…', $cut);
    $this->assertLessThanOrEqual(60, mb_strlen($cut));
    $this->assertStringNotContainsString('palabr…', $cut, 'the cut lands between words');
  }

}
