<?php

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../../includes/myapi.claim_transaction_admin.inc';

/**
 * Unit tests for the autogenerated title of a 'claim_transaction' (SPEC 60),
 * composed by myapi_claim_transaction_title() in
 * includes/myapi.claim_transaction_admin.inc.
 *
 * The bug this spec fixes is that a transaction created from the timeline's own
 * page (SPEC 57) was saved with node.title = '' — the column is NOT NULL
 * DEFAULT '', so node_save() never complained and the operator got an empty
 * link in /admin/content. These tests pin the replacement format down to the
 * character, because it is the only thing that identifies a transaction outside
 * the claim's timeline.
 *
 * Deliberately NOT tested here, and said out loud rather than skipped in
 * silence (same criterion as ClaimTransactionEditTest with
 * myapi_claim_transaction_edit_link()):
 *   - myapi_claim_transaction_set_title(), which reads the four values off the
 *     node and resolves the status label through myapi_claims_status_options()
 *     — Field API, i.e. exactly what tests/unit avoids. Its field reads are
 *     already covered by BuildingAdminTest.
 *   - The hook_node_presave() branch in myapi.module, three lines of glue.
 *   - myapi_update_7020(), which is database only.
 * All three are in the spec's manual acceptance matrix instead.
 *
 * The two length tests are guards against a future edit rather than checks of
 * today's output: testCommentExactlyAtTheLimitIsNotTruncated() fails the moment
 * the ellipsis starts being appended to a comment that fits, and
 * testTitleNeverExceedsTheColumnLength() fails if the final truncation is ever
 * dropped — which would make node_save() silently cut the title at the varchar
 * boundary instead, mid-character.
 */
class ClaimTransactionTitleTest extends TestCase {

  /**
   * The stored value of field_status_date, as Date module leaves it by the time
   * hook_node_presave() runs: a full 'Y-m-d H:i:s' string (SPEC 58).
   */
  const STATUS_DATE = '2026-08-03 14:30:00';

  /**
   * That same instant as the title renders it, 'd/m/Y H:i' — the format the
   * timeline already uses for this column.
   */
  const STATUS_DATE_RENDERED = '03/08/2026 14:30';

  public function testAllFourValuesPresent() {
    $title = myapi_claim_transaction_title(128, 'En proceso', self::STATUS_DATE, 'Se coordinó la visita');

    $this->assertSame('Reclamo #128 · En proceso · ' . self::STATUS_DATE_RENDERED . ' · Se coordinó la visita', $title);
  }

  /**
   * The automatic initial transaction of a claim (SPEC 57) has no comment: the
   * title has to end at the date, with no dangling separator.
   */
  public function testWithoutCommentTheSeparatorDoesNotDangle() {
    $title = myapi_claim_transaction_title(128, 'Recibido', self::STATUS_DATE, NULL);

    $this->assertSame('Reclamo #128 · Recibido · ' . self::STATUS_DATE_RENDERED, $title);
  }

  public function testLongCommentIsTruncatedOnAWordBoundaryWithEllipsis() {
    $comment = 'Se contactó al proveedor para agendar la visita técnica del lunes';
    $this->assertGreaterThan(60, mb_strlen($comment), 'Fixture must exceed the 60 character budget.');

    $title = myapi_claim_transaction_title(128, 'En proceso', self::STATUS_DATE, $comment);

    $this->assertStringEndsWith('…', $title);
    $this->assertStringContainsString('Se contactó al proveedor para agendar la visita técnica', $title);
    // The word that did not fit is gone whole — not cut in half.
    $this->assertStringNotContainsString('lun', $title);
  }

  public function testCommentExactlyAtTheLimitIsNotTruncated() {
    $comment = 'Cambio de estado registrado tras la visita del proveedor hoy';
    $this->assertSame(60, mb_strlen($comment), 'Fixture must be exactly at the 60 character budget.');

    $title = myapi_claim_transaction_title(128, 'Resuelto', self::STATUS_DATE, $comment);

    $this->assertStringEndsWith($comment, $title);
    $this->assertStringNotContainsString('…', $title);
  }

  /**
   * field_comment is a textarea: a title carrying its newlines renders broken
   * in /admin/content.
   */
  public function testCommentWhitespaceIsCollapsedToASingleLine() {
    $title = myapi_claim_transaction_title(128, 'En proceso', self::STATUS_DATE, "  Se llamó\nal   plomero\t\n");

    $this->assertSame('Reclamo #128 · En proceso · ' . self::STATUS_DATE_RENDERED . ' · Se llamó al plomero', $title);
  }

  public function testWhitespaceOnlyCommentCountsAsAbsent() {
    $title = myapi_claim_transaction_title(128, 'En proceso', self::STATUS_DATE, "  \n\t ");

    $this->assertSame('Reclamo #128 · En proceso · ' . self::STATUS_DATE_RENDERED, $title);
  }

  /**
   * The corrupt-data case SPEC 56/57 already document: field_claim empty or
   * pointing nowhere. The segment goes, the rest still reads correctly.
   *
   * @dataProvider missingClaimNidProvider
   */
  public function testWithoutClaimNidTheFirstSegmentIsDropped($claim_nid) {
    $title = myapi_claim_transaction_title($claim_nid, 'En proceso', self::STATUS_DATE, 'Sin reclamo');

    $this->assertSame('En proceso · ' . self::STATUS_DATE_RENDERED . ' · Sin reclamo', $title);
  }

  public function missingClaimNidProvider() {
    return array(
      'null' => array(NULL),
      'zero' => array(0),
      'zero as string' => array('0'),
      'empty string' => array(''),
    );
  }

  public function testWithoutStatusLabelThatSegmentIsDropped() {
    $title = myapi_claim_transaction_title(128, NULL, self::STATUS_DATE, 'Sin estado');

    $this->assertSame('Reclamo #128 · ' . self::STATUS_DATE_RENDERED . ' · Sin estado', $title);
  }

  /**
   * A stored value with no label in the catalogue falls back to the raw value —
   * the caller resolves it, same semantics myapi_claims_status_label() already
   * has for the timeline.
   */
  public function testUncataloguedStatusIsPrintedRaw() {
    $title = myapi_claim_transaction_title(128, 'escalated', self::STATUS_DATE, NULL);

    $this->assertSame('Reclamo #128 · escalated · ' . self::STATUS_DATE_RENDERED, $title);
  }

  /**
   * @dataProvider unusableStatusDateProvider
   */
  public function testUnusableStatusDateDropsTheSegment($status_date) {
    $title = myapi_claim_transaction_title(128, 'En proceso', $status_date, 'Sin fecha');

    $this->assertSame('Reclamo #128 · En proceso · Sin fecha', $title);
  }

  public function unusableStatusDateProvider() {
    return array(
      'null' => array(NULL),
      'empty string' => array(''),
      // No 1970 fallback: strtotime() fails and the segment is dropped, rather
      // than printing 01/01/1970 as if it were a real status date.
      'not a date' => array('cuando se pueda'),
    );
  }

  public function testNothingResolvesFallsBackToAGenericTitle() {
    $title = myapi_claim_transaction_title(NULL, NULL, NULL, NULL);

    $this->assertSame('Transacción de reclamo', $title);
  }

  /**
   * node.title is varchar(255). The status label comes from field_status'
   * allowed_values, which an administrator can edit to anything.
   */
  public function testTitleNeverExceedsTheColumnLength() {
    $title = myapi_claim_transaction_title(128, str_repeat('a', 300), self::STATUS_DATE, 'Comentario');

    $this->assertLessThanOrEqual(255, mb_strlen($title));
  }

  /**
   * node.title is stored raw and escaped by Drupal at render time, so nothing
   * here may run check_plain() — that is why the status label comes from
   * myapi_claims_status_options() and not from myapi_claims_status_label().
   */
  public function testTitleIsNotHtmlEscaped() {
    $title = myapi_claim_transaction_title(128, 'En proceso', self::STATUS_DATE, 'Cañería rota & humedad en el <sótano>');

    $this->assertStringEndsWith('Cañería rota & humedad en el <sótano>', $title);
    $this->assertStringNotContainsString('&amp;', $title);
    $this->assertStringNotContainsString('&lt;', $title);
  }

}
