<?php

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../../includes/myapi.claim_transaction_admin.inc';

/**
 * Unit tests for the acknowledgement comment of the automatic initial
 * transaction (SPEC 61), composed by
 * myapi_claim_transaction_initial_comment() in
 * includes/myapi.claim_transaction_admin.inc.
 *
 * The text is what the resident reads back as proof the claim was received, so
 * these tests pin it to the character — including the noun, which is the only
 * part that varies (field_claim_type: 'claim' or 'requirement').
 *
 * Deliberately NOT tested here, and said out loud rather than skipped in
 * silence (same criterion as ClaimTransactionTitleTest):
 *   - myapi_claim_transaction_create_initial(), which reads field_claim_type
 *     off the claim and node_save()s the transaction — Field API plus the
 *     database, i.e. exactly what tests/unit avoids. Its field read goes
 *     through myapi_building_admin_field_value(), already covered by
 *     BuildingAdminTest.
 *   - The hook_node_insert() branch in myapi.module, three lines of glue.
 * Both are in the spec's manual acceptance matrix instead.
 */
class ClaimTransactionInitialCommentTest extends TestCase {

  /**
   * Everything after the noun, which no stored value changes: both nouns are
   * masculine, so the sentence has no gender-dependent branch.
   */
  const TAIL = '. Será revisado por la administración y se le notificará cualquier novedad.';

  public function testClaimUsesTheClaimNoun() {
    $this->assertSame(
      'Hemos recibido su reclamo' . self::TAIL,
      myapi_claim_transaction_initial_comment('claim')
    );
  }

  public function testRequirementUsesTheRequirementNoun() {
    $this->assertSame(
      'Hemos recibido su requerimiento' . self::TAIL,
      myapi_claim_transaction_initial_comment('requirement')
    );
  }

  /**
   * field_claim_type is required on the 'reclamo' bundle, so a missing value
   * means corrupt data — the same case SPEC 56/57 already document for
   * field_claim. The transaction still gets a comment rather than falling back
   * to the empty timeline row this spec exists to remove.
   */
  public function testMissingTypeFallsBackToTheClaimNoun() {
    $expected = 'Hemos recibido su reclamo' . self::TAIL;

    $this->assertSame($expected, myapi_claim_transaction_initial_comment(NULL));
    $this->assertSame($expected, myapi_claim_transaction_initial_comment(''));
  }

  /**
   * An allowed_value invented later from the UI is not a third noun: only
   * 'requirement' branches, everything else reads as a claim.
   */
  public function testUnknownTypeFallsBackToTheClaimNoun() {
    $this->assertSame(
      'Hemos recibido su reclamo' . self::TAIL,
      myapi_claim_transaction_initial_comment('suggestion')
    );
  }

  /**
   * The comment is a single line: it travels into SPEC 60's autogenerated
   * title, where a newline would render broken. Guard against a future edit
   * that splits the sentence in two.
   */
  public function testCommentIsASingleLine() {
    $this->assertSame(
      1,
      preg_match('/^[^\r\n]+$/u', myapi_claim_transaction_initial_comment('claim'))
    );
  }

  /**
   * Since SPEC 61 the initial transaction is no longer commentless, so its
   * autogenerated title (SPEC 60) gains the fourth segment — truncated to the
   * usual 60 characters, on a word boundary, ending in an ellipsis.
   */
  public function testTheCommentReachesTheAutogeneratedTitle() {
    $title = myapi_claim_transaction_title(
      128,
      'Recibido',
      '2026-08-03 14:30:00',
      myapi_claim_transaction_initial_comment('requirement')
    );

    $this->assertSame(
      'Reclamo #128 · Recibido · 03/08/2026 14:30 · Hemos recibido su requerimiento. Será revisado por la…',
      $title
    );
  }

}
