<?php

use PHPUnit\Framework\TestCase;

// Both includes, and in this order: module_load_include() is a no-op in
// tests/unit/bootstrap.php, so the catalogue myapi.service_transaction.inc
// loads at file scope would simply not exist here without the first require.
require_once __DIR__ . '/../../includes/myapi.services_common.inc';
require_once __DIR__ . '/../../includes/myapi.service_transaction.inc';

/**
 * Unit tests for the automatic initial transaction of a 'service_request'
 * (SPEC 92): the three acknowledgement texts and the autogenerated title, both
 * in includes/myapi.service_transaction.inc.
 *
 * The two things pinned here are the two the operator and the resident read
 * back. The acknowledgement is the proof the request was received, and the
 * title is the only thing that identifies a transaction in /admin/content —
 * where, until this spec, every automatic transaction would have shown up as a
 * blank link, node.title being NOT NULL DEFAULT '' (the exact hole SPEC 60
 * closed for claims, and the reason the title is inside this spec at all).
 *
 * Deliberately NOT tested here, and said out loud rather than skipped in
 * silence (same criterion as ClaimTransactionTitleTest):
 *   - myapi_service_transaction_set_title(), which reads the four values off
 *     the node — Field API, i.e. exactly what tests/unit avoids. Its field
 *     reads go through myapi_building_admin_field_value() /
 *     _field_target_id(), already covered by BuildingAdminTest.
 *   - myapi_service_transaction_create_initial(), which node_save()s the
 *     transaction: Field API plus the database.
 * Both are in the spec's manual acceptance matrix instead. What IS covered of
 * them is that the two hook branches delegating to them still exist — the two
 * guards at the bottom, which read myapi.module as text, the same resource
 * ServicesInstallTest already uses on myapi.install.
 *
 * The two length tests are guards against a future edit rather than checks of
 * today's output: testCommentExactlyAtTheLimitIsNotTruncated() fails the moment
 * the ellipsis starts being appended to a comment that fits, and
 * testTitleNeverExceedsTheColumnLength() fails if the final truncation is ever
 * dropped — which would make node_save() silently cut the title at the varchar
 * boundary instead, mid-character.
 */
class ServiceTransactionTest extends TestCase {

  /**
   * The stored value of field_status_date by the time hook_node_presave() runs:
   * a full 'Y-m-d H:i:s' string. The creator writes it with the seconds pinned
   * to ':00' — the real instant of the creation, not that day at midnight.
   */
  const STATUS_DATE = '2026-08-19 14:30:00';

  /**
   * That same instant as the title renders it, 'd/m/Y H:i'.
   */
  const STATUS_DATE_RENDERED = '19/08/2026 14:30';

  /* -------------------------------------------------------------------------
   * The three acknowledgement texts.
   * ---------------------------------------------------------------------- */

  /**
   * 'open': the request is out for offers. First person, addressed to the
   * resident, and a different promise from 'direct' below — which is the whole
   * reason there is more than one text.
   */
  public function testOpenGetsTheOfferingAcknowledgement() {
    $this->assertSame(
      'Hemos recibido su solicitud. Los proveedores de la categoría podrán enviarle ofertas y se le notificará cualquier novedad.',
      myapi_service_transaction_initial_comment(MYAPI_SERVICES_REQUEST_STATUS_OPEN)
    );
  }

  /**
   * 'direct' (SPEC 87): the resident went straight to one provider, so nobody
   * is going to bid. Announcing offers here would be a promise the request
   * cannot keep.
   */
  public function testDirectGetsTheChosenProviderAcknowledgement() {
    $this->assertSame(
      'Hemos recibido su solicitud y fue enviada al proveedor seleccionado. Se le notificará cualquier novedad.',
      myapi_service_transaction_initial_comment(MYAPI_SERVICES_REQUEST_STATUS_DIRECT)
    );
  }

  public function testTheTwoBirthStatusesReadDifferently() {
    $this->assertNotSame(
      myapi_service_transaction_initial_comment(MYAPI_SERVICES_REQUEST_STATUS_OPEN),
      myapi_service_transaction_initial_comment(MYAPI_SERVICES_REQUEST_STATUS_DIRECT)
    );
  }

  /**
   * A request an operator registers from the back office already closed,
   * cancelled, offered or assigned is not acknowledging receipt of anything: it
   * is an administrative record, and the text says so — with the catalogue's
   * LABEL, never the stored key.
   *
   * @dataProvider catalogueStatusProvider
   */
  public function testACatalogueStatusUsesItsLabelAndNotItsKey($status, $label) {
    $comment = myapi_service_transaction_initial_comment($status);

    $this->assertSame('Solicitud registrada con estado ' . $label . '.', $comment);
    $this->assertStringNotContainsString($status, $comment);
  }

  public function catalogueStatusProvider() {
    return array(
      'offered' => array(MYAPI_SERVICES_REQUEST_STATUS_OFFERED, 'Con ofertas'),
      'assigned' => array(MYAPI_SERVICES_REQUEST_STATUS_ASSIGNED, 'Asignada'),
      'closed' => array(MYAPI_SERVICES_REQUEST_STATUS_CLOSED, 'Cerrada'),
      'cancelled' => array(MYAPI_SERVICES_REQUEST_STATUS_CANCELLED, 'Cancelada'),
    );
  }

  /**
   * The label comes from myapi_services_request_statuses() and is not
   * transcribed here, so this test reads the catalogue too: renaming a label
   * changes the text with no edit to includes/myapi.service_transaction.inc.
   * It fails the day someone hardcodes the four strings back in.
   */
  public function testTheLabelIsReadFromTheCatalogue() {
    $statuses = myapi_services_request_statuses();

    foreach ($statuses as $status => $label) {
      if ($status === MYAPI_SERVICES_REQUEST_STATUS_OPEN || $status === MYAPI_SERVICES_REQUEST_STATUS_DIRECT) {
        continue;
      }
      $this->assertSame(
        'Solicitud registrada con estado ' . $label . '.',
        myapi_service_transaction_initial_comment($status)
      );
    }
  }

  /**
   * A key that is not in the catalogue at all — an allowed_value invented later
   * — degrades to the same generic text with the raw key, never to an empty
   * comment and never to an error. A transaction is not born commentless.
   */
  public function testAnUnknownKeyFallsBackToTheRawValue() {
    $this->assertSame(
      'Solicitud registrada con estado paused.',
      myapi_service_transaction_initial_comment('paused')
    );
  }

  /**
   * No status at all: possible only through a careless programmatic
   * node_save(), since neither the form nor SPEC 90's builder omits it. No
   * dangling '@estado', and still a comment.
   *
   * @dataProvider absentStatusProvider
   */
  public function testAnAbsentStatusGetsTheBareRecordText($status) {
    $comment = myapi_service_transaction_initial_comment($status);

    $this->assertSame('Solicitud registrada.', $comment);
    $this->assertStringNotContainsString('@estado', $comment);
  }

  public function absentStatusProvider() {
    return array(
      'null' => array(NULL),
      'empty string' => array(''),
      'whitespace only' => array("  \n\t "),
    );
  }

  /**
   * Every variant is a single line: the comment travels into the title, where a
   * newline renders broken. Guard against a future edit that splits a sentence
   * in two.
   */
  public function testEveryAcknowledgementIsASingleLine() {
    $statuses = array_merge(array(NULL, '', 'paused'), array_keys(myapi_services_request_statuses()));

    foreach ($statuses as $status) {
      $this->assertSame(
        1,
        preg_match('/^[^\r\n]+$/u', myapi_service_transaction_initial_comment($status)),
        'Acknowledgement of ' . var_export($status, TRUE) . ' must be one line.'
      );
    }
  }

  /* -------------------------------------------------------------------------
   * The autogenerated title.
   * ---------------------------------------------------------------------- */

  public function testAllFourValuesPresent() {
    $title = myapi_service_transaction_title(412, 'Abierta', self::STATUS_DATE, 'Se coordinó la visita');

    $this->assertSame('Solicitud #412 · Abierta · ' . self::STATUS_DATE_RENDERED . ' · Se coordinó la visita', $title);
  }

  /**
   * A transaction saved by hand from node/add/service_transaction with the
   * comment left empty has to end at the date, with no dangling separator.
   */
  public function testWithoutCommentTheSeparatorDoesNotDangle() {
    $title = myapi_service_transaction_title(412, 'Abierta', self::STATUS_DATE, NULL);

    $this->assertSame('Solicitud #412 · Abierta · ' . self::STATUS_DATE_RENDERED, $title);
  }

  /**
   * The corrupt-data case: field_request empty or pointing nowhere. The first
   * segment goes, and nothing dangles at the START of the title either.
   *
   * @dataProvider missingRequestNidProvider
   */
  public function testWithoutRequestNidTheFirstSegmentIsDropped($request_nid) {
    $title = myapi_service_transaction_title($request_nid, 'Abierta', self::STATUS_DATE, 'Sin solicitud');

    $this->assertSame('Abierta · ' . self::STATUS_DATE_RENDERED . ' · Sin solicitud', $title);
  }

  public function missingRequestNidProvider() {
    return array(
      'null' => array(NULL),
      'zero' => array(0),
      'zero as string' => array('0'),
      'empty string' => array(''),
    );
  }

  public function testWithoutStatusLabelThatSegmentIsDropped() {
    $title = myapi_service_transaction_title(412, NULL, self::STATUS_DATE, 'Sin estado');

    $this->assertSame('Solicitud #412 · ' . self::STATUS_DATE_RENDERED . ' · Sin estado', $title);
  }

  /**
   * The caller resolves the label; a key with no entry in the catalogue arrives
   * raw and is printed raw — same semantics as the generic acknowledgement.
   */
  public function testAnUnresolvedStatusLabelIsPrintedAsItArrives() {
    $title = myapi_service_transaction_title(412, 'paused', self::STATUS_DATE, NULL);

    $this->assertSame('Solicitud #412 · paused · ' . self::STATUS_DATE_RENDERED, $title);
  }

  public function testWithoutStatusDateThatSegmentIsDropped() {
    $title = myapi_service_transaction_title(412, 'Abierta', NULL, 'Sin fecha');

    $this->assertSame('Solicitud #412 · Abierta · Sin fecha', $title);
  }

  /**
   * The point of strtotime() over a format assumption: an unparseable value
   * DROPS the segment instead of printing 01/01/1970 as if it were a real
   * status date.
   *
   * @dataProvider unparseableDateProvider
   */
  public function testAnUnparseableDateDropsTheSegmentInsteadOfPrintingTheEpoch($status_date) {
    $title = myapi_service_transaction_title(412, 'Abierta', $status_date, 'Fecha ilegible');

    $this->assertSame('Solicitud #412 · Abierta · Fecha ilegible', $title);
    $this->assertStringNotContainsString('1970', $title);
  }

  /**
   * '0000-00-00 00:00:00' is deliberately NOT here: strtotime() parses it into
   * a real (negative) timestamp rather than returning FALSE, so the segment
   * survives as '30/11/-0001'. That is outside what SPEC 92 asks of this
   * function — and outside what a 'datetime' field can store, since the Date
   * module writes either NULL or a valid instant — so it is left as the
   * existing behaviour, identical to claims', instead of being pinned here.
   */
  public function unparseableDateProvider() {
    return array(
      'empty string' => array(''),
      'not a date' => array('no es una fecha'),
      'only a label' => array('pendiente'),
    );
  }

  /**
   * The promise this spec makes: a transaction is never titleless. With nothing
   * resolvable at all the fallback still names what the node is.
   */
  public function testWithNothingResolvableTheFallbackTitleIsUsed() {
    $title = myapi_service_transaction_title(NULL, NULL, NULL, NULL);

    $this->assertSame('Transacción de solicitud', $title);
    $this->assertNotSame('', $title);
  }

  public function testWhitespaceOnlyValuesAlsoReachTheFallback() {
    $this->assertSame(
      'Transacción de solicitud',
      myapi_service_transaction_title('', "  \n ", '', "  \t\n ")
    );
  }

  /* -------------------------------------------------------------------------
   * The comment inside the title.
   * ---------------------------------------------------------------------- */

  public function testLongCommentIsTruncatedOnAWordBoundaryWithEllipsis() {
    $comment = 'Se contactó al proveedor para agendar la visita técnica del lunes';
    $this->assertGreaterThan(60, mb_strlen($comment), 'Fixture must exceed the 60 character budget.');

    $title = myapi_service_transaction_title(412, 'Abierta', self::STATUS_DATE, $comment);

    $this->assertStringEndsWith('…', $title);
    $this->assertStringContainsString('Se contactó al proveedor para agendar la visita técnica', $title);
    // The word that did not fit is gone whole — not cut in half.
    $this->assertStringNotContainsString('lun', $title);
  }

  public function testCommentExactlyAtTheLimitIsNotTruncated() {
    $comment = 'Cambio de estado registrado tras la visita del proveedor hoy';
    $this->assertSame(60, mb_strlen($comment), 'Fixture must be exactly at the 60 character budget.');

    $title = myapi_service_transaction_title(412, 'Cerrada', self::STATUS_DATE, $comment);

    $this->assertStringEndsWith($comment, $title);
    $this->assertStringNotContainsString('…', $title);
  }

  /**
   * field_comment is a textarea: a title carrying its newlines renders broken
   * in /admin/content. Collapsed BEFORE the cut, so no part of the 60-character
   * budget is spent on whitespace.
   */
  public function testCommentWhitespaceIsCollapsedToASingleLine() {
    $title = myapi_service_transaction_title(412, 'Abierta', self::STATUS_DATE, "  Se llamó\nal   plomero\t\n");

    $this->assertSame('Solicitud #412 · Abierta · ' . self::STATUS_DATE_RENDERED . ' · Se llamó al plomero', $title);
  }

  public function testWhitespaceOnlyCommentCountsAsAbsent() {
    $this->assertSame('', myapi_service_transaction_title_comment("  \n\t "));
    $this->assertSame('', myapi_service_transaction_title_comment(NULL));
  }

  /**
   * The acknowledgement of 'open' is longer than the budget, so the automatic
   * transaction exercises the truncation on its very first row. Pinned whole:
   * this is literally what /admin/content shows for a request born open.
   */
  public function testTheAcknowledgementReachesTheAutogeneratedTitle() {
    $title = myapi_service_transaction_title(
      412,
      'Abierta',
      self::STATUS_DATE,
      myapi_service_transaction_initial_comment(MYAPI_SERVICES_REQUEST_STATUS_OPEN)
    );

    $this->assertSame(
      'Solicitud #412 · Abierta · ' . self::STATUS_DATE_RENDERED . ' · Hemos recibido su solicitud. Los proveedores de la…',
      $title
    );
  }

  /* -------------------------------------------------------------------------
   * The 255 ceiling.
   * ---------------------------------------------------------------------- */

  /**
   * node.title / node_revision.title are varchar(255). Without the final
   * truncate_utf8() MySQL would cut the value itself, mid-character on a UTF-8
   * string. The status label is the only segment with no length limit of its
   * own, so it is what this fixture stretches.
   */
  public function testTitleNeverExceedsTheColumnLength() {
    $title = myapi_service_transaction_title(
      412,
      str_repeat('á', 400),
      self::STATUS_DATE,
      'Comentario'
    );

    $this->assertLessThanOrEqual(255, mb_strlen($title));
    // Cut on a character boundary, not inside a multi-byte sequence.
    $this->assertSame($title, mb_convert_encoding($title, 'UTF-8', 'UTF-8'));
  }

  /* -------------------------------------------------------------------------
   * The two hook branches (guards).
   * ---------------------------------------------------------------------- */

  /**
   * The creator only ever runs because of this branch. Without it every request
   * is silently born with no timeline at all — nothing fails, nothing logs, the
   * row simply is not there. Reading the module as text is the same resource
   * ServicesInstallTest uses on myapi.install: the alternative is booting
   * Drupal, which tests/unit does not do.
   */
  public function testNodeInsertStillDelegatesForAServiceRequest() {
    $module = $this->moduleSource();

    $this->assertStringContainsString("if (\$node->type === 'service_request') {", $module);
    $this->assertStringContainsString('myapi_service_transaction_create_initial($node);', $module);
  }

  /**
   * Without this branch the automatic transaction is created all the same, but
   * with title = '' — the blank link in /admin/content this spec exists to
   * prevent.
   */
  public function testNodePresaveStillDelegatesForAServiceTransaction() {
    $module = $this->moduleSource();

    $this->assertStringContainsString("if (\$node->type === 'service_transaction') {", $module);
    $this->assertStringContainsString('myapi_service_transaction_set_title($node);', $module);
  }

  /**
   * SPEC 92 keeps the direction request -> transaction and only that. A
   * 'service_transaction' branch in hook_node_INSERT() would be the first half
   * of a cascade; this guard makes adding one a deliberate, visible act.
   */
  public function testNodeInsertHasNoServiceTransactionBranch() {
    $insert = $this->functionSource('myapi_node_insert');

    $this->assertStringNotContainsString("'service_transaction'", $insert);
  }

  /**
   * @return string
   *   myapi.module as text.
   */
  private function moduleSource() {
    return file_get_contents(__DIR__ . '/../../myapi.module');
  }

  /**
   * The body of one function of myapi.module, from its declaration to the next
   * one — enough to assert what a single hook does and does not contain.
   *
   * @param string $name
   *
   * @return string
   */
  private function functionSource($name) {
    $module = $this->moduleSource();
    $start = strpos($module, 'function ' . $name . '(');
    $this->assertNotFalse($start, $name . '() must exist in myapi.module.');

    $end = strpos($module, "\n}\n", $start);
    $this->assertNotFalse($end, $name . '() must be closed.');

    return substr($module, $start, $end - $start);
  }

}
