<?php

use PHPUnit\Framework\TestCase;

// Both includes, and in this order: module_load_include() is a no-op in
// tests/unit/bootstrap.php, so the catalogue myapi.service_rating.inc loads at
// file scope would simply not exist here without the first require.
require_once __DIR__ . '/../../includes/myapi.services_common.inc';
require_once __DIR__ . '/../../includes/myapi.service_rating.inc';

/**
 * Unit tests for the pure half of includes/myapi.service_rating.inc
 * (SPEC 108): what actually goes into a provider's two reputation counters,
 * and the autogenerated title of a rating.
 *
 * These two counters are read by the provider listing and by the provider
 * detail on every request of the marketplace, and until this spec NOTHING had
 * ever written them — every provider answered `rating_avg: null` and
 * `rating_count: 0`. What is pinned here is the last step before the write, so
 * a rounding or an empty-value rule cannot drift without a test going red.
 *
 * Deliberately NOT tested here, and said out loud rather than skipped in
 * silence (same criterion as ServiceTransactionTest):
 *   - myapi_service_rating_provider_aggregates(), which is SQL — one grouped
 *     query over three tables. Its whole contract is that it counts EXACTLY the
 *     rows myapi_provider_rating_summary() counts, and only a booted site can
 *     prove that.
 *   - myapi_service_rating_sync_provider() and myapi_service_rating_record(),
 *     which node_load() and node_save(): Field API plus the database.
 *   - myapi_service_rating_set_title(), which reads the fields off the node and
 *     loads the provider. Its field reads go through
 *     myapi_building_admin_field_value() / _field_target_id(), already covered
 *     by BuildingAdminTest.
 * All four are in the spec's manual acceptance matrix instead, and the $exclude
 * _nid of the deletion is there for a reason no unit test could reach: it
 * depends on the ORDER Drupal 7 fires hook_node_delete() in, which is a fact
 * about a booted site and not about this code. What IS covered of them here is
 * that the four hook branches delegating to them still exist — the guards at
 * the bottom, which read myapi.module as text, the same resource
 * ServiceTransactionTest already uses.
 */
class ServiceRatingAggregatesTest extends TestCase {

  /* -------------------------------------------------------------------------
   * What gets written into the two counters.
   * ---------------------------------------------------------------------- */

  /**
   * NOTHING RATED YET: the count is a stored ZERO and the average is ABSENT.
   *
   * The two halves are different decisions and both matter. The zero is written
   * because the API already answers 0 for an empty count, so storing it makes
   * storage and API say the same thing. The average is left empty because an
   * unrated provider does not have a zero for a mark — 0.00 is outside the 1-5
   * scale and the app paints "sin valoraciones" off exactly this NULL.
   */
  public function testNoRatingsStoresZeroAndNoAverage() {
    $result = myapi_service_rating_format_average(0, NULL);

    $this->assertSame(0, $result['count']);
    $this->assertNull($result['average']);
  }

  /**
   * The same answer however the emptiness arrives — a count that came back as
   * the string '0' from an aggregate, or a negative one from a corrupt row.
   */
  public function testEveryShapeOfEmptinessAnswersTheSameWay() {
    foreach ([0, '0', -1, NULL, ''] as $count) {
      $result = myapi_service_rating_format_average($count, 4.5);

      $this->assertSame(0, $result['count']);
      $this->assertNull($result['average']);
    }
  }

  /**
   * One five-star rating: count 1, average 5.00 — and the average is a FLOAT,
   * not the string '5.00'. The app reads a JSON number.
   */
  public function testASingleRatingIsItsOwnAverage() {
    $result = myapi_service_rating_format_average(1, 5);

    $this->assertSame(1, $result['count']);
    $this->assertSame(5.0, $result['average']);
  }

  /**
   * TWO DECIMALS, because field_rating_avg is number_decimal(3, 2): it holds
   * 0.00 to 9.99 and a third decimal would be lost on the write, silently.
   */
  public function testTheAverageIsRoundedToTwoDecimals() {
    $result = myapi_service_rating_format_average(3, 4.666666666666667);

    $this->assertSame(3, $result['count']);
    $this->assertSame(4.67, $result['average']);
  }

  /**
   * The 4.50 of the acceptance matrix — a 5 and a 4 — comes out exact.
   */
  public function testAnExactHalfStarAverageSurvivesTheRounding() {
    $result = myapi_service_rating_format_average(2, 4.5);

    $this->assertSame(2, $result['count']);
    $this->assertSame(4.5, $result['average']);
  }

  /**
   * A value already sitting on the boundary keeps at most two decimals and
   * never grows a third. Asserted as a property rather than against one
   * hardcoded number: what must hold is that the stored value survives its own
   * rounding, whichever way the platform breaks the tie on 3.005.
   */
  public function testNoAverageEverCarriesAThirdDecimal() {
    foreach ([3.005, 1.115, 2.675, 4.999, 3.333333333] as $raw) {
      $average = myapi_service_rating_format_average(2, $raw)['average'];

      $this->assertSame($average, round($average, 2), 'Average of ' . $raw . ' kept a third decimal.');
      $this->assertGreaterThanOrEqual(1.0, $average);
      $this->assertLessThanOrEqual(5.0, $average);
    }
  }

  /**
   * A numeric string average — which is what an aggregate query hands back on
   * several database drivers — is a number, not a refusal.
   */
  public function testANumericStringAverageIsAccepted() {
    $result = myapi_service_rating_format_average('4', '4.6666');

    $this->assertSame(4, $result['count']);
    $this->assertSame(4.67, $result['average']);
  }

  /**
   * A count with no average at all: the count is TRUE and is kept, and the mark
   * that cannot be computed is left ABSENT rather than invented as a zero. The
   * INNER JOIN of the aggregate makes this unreachable today; it is written so
   * that a broken row cannot push a provider's reputation to 0.00.
   */
  public function testACountWithNoAverageKeepsTheCountAndLeavesTheMarkEmpty() {
    foreach ([NULL, '', 'nan'] as $average) {
      $result = myapi_service_rating_format_average(4, $average);

      $this->assertSame(4, $result['count']);
      $this->assertNull($result['average']);
    }
  }

  /* -------------------------------------------------------------------------
   * The title of a rating.
   * ---------------------------------------------------------------------- */

  /**
   * How the title renders a date: 'd/m/Y' — the day and not the minute. A
   * rating is not an event whose exact time anybody reads back.
   */
  const CREATED_RENDERED = '28/08/2026';

  /**
   * The fixture instant, built with mktime() and not hardcoded: the stub of
   * format_date() maps onto date(), so a literal timestamp would render a
   * different day on a machine in another timezone. Same convention as every
   * other date fixture of this suite.
   *
   * @return int
   */
  private function created() {
    return mktime(9, 14, 0, 8, 28, 2026);
  }

  /**
   * The whole title, with everything present.
   */
  public function testTheFullTitleCarriesTheFourSegments() {
    $title = myapi_service_rating_title('Plomería Ruiz', 5, $this->created());

    $this->assertSame(
      'Calificación · Plomería Ruiz · 5★ · ' . self::CREATED_RENDERED,
      $title
    );
  }

  /**
   * No provider name — a deleted provider, or a broken reference: the segment
   * simply goes, and no separator is left dangling.
   */
  public function testAMissingProviderNameDropsItsSegment() {
    foreach ([NULL, '', '   '] as $name) {
      $title = myapi_service_rating_title($name, 4, $this->created());

      $this->assertSame('Calificación · 4★ · ' . self::CREATED_RENDERED, $title);
      $this->assertStringNotContainsString('· ·', $title);
    }
  }

  /**
   * A provider name arrives trimmed into the title, so a stray space in
   * node.title cannot produce a double separator.
   */
  public function testTheProviderNameIsTrimmed() {
    $title = myapi_service_rating_title('  Plomería Ruiz  ', 5, $this->created());

    $this->assertSame(
      'Calificación · Plomería Ruiz · 5★ · ' . self::CREATED_RENDERED,
      $title
    );
  }

  /**
   * No stars — a rating whose required field is somehow empty: the segment
   * goes, rather than printing '0★' for a broken node.
   */
  public function testMissingStarsDropTheirSegment() {
    foreach ([NULL, '', 'abc', []] as $stars) {
      $title = myapi_service_rating_title('Plomería Ruiz', $stars, $this->created());

      $this->assertSame(
        'Calificación · Plomería Ruiz · ' . self::CREATED_RENDERED,
        $title
      );
      $this->assertStringNotContainsString('★', $title);
    }
  }

  /**
   * A digit string of stars renders as the number, so a value that came out of
   * the field API as a string does not lose its segment.
   */
  public function testDigitStringStarsRenderAsTheNumber() {
    $this->assertSame(
      myapi_service_rating_title('Plomería Ruiz', 5, $this->created()),
      myapi_service_rating_title('Plomería Ruiz', '5', $this->created())
    );
  }

  /**
   * An unparseable date drops its segment instead of printing 01/01/1970 as if
   * it were a real one. A timestamp of 0 is exactly what an unset integer
   * column looks like, which is why it is in this list and not in the one
   * above.
   */
  public function testAnUnparseableDateDropsItsSegment() {
    foreach ([NULL, '', 0, '0', -1, 'not a date', []] as $created) {
      $title = myapi_service_rating_title('Plomería Ruiz', 5, $created);

      $this->assertSame('Calificación · Plomería Ruiz · 5★', $title);
      $this->assertStringEndsNotWith('·', $title);
    }
  }

  /**
   * A 'Y-m-d H:i:s' string is accepted as well as an integer, so a created
   * column handed over by a migration renders instead of vanishing.
   */
  public function testADateStringIsAcceptedToo() {
    $title = myapi_service_rating_title('Plomería Ruiz', 5, '2026-08-28 09:14:00');

    $this->assertSame(
      'Calificación · Plomería Ruiz · 5★ · ' . self::CREATED_RENDERED,
      $title
    );
  }

  /**
   * Everything missing at once: the title is still readable and never empty.
   * node.title is NOT NULL DEFAULT '', so the alternative is a blank link in
   * /admin/content — the exact hole this generator exists to close.
   */
  public function testATitleIsNeverEmpty() {
    $this->assertSame('Calificación', myapi_service_rating_title(NULL, NULL, NULL));

    foreach ([NULL, '', 'Plomería Ruiz'] as $name) {
      foreach ([NULL, '', 0, 5] as $stars) {
        foreach ([NULL, '', 0, $this->created()] as $created) {
          $title = myapi_service_rating_title($name, $stars, $created);

          $this->assertIsString($title);
          $this->assertNotSame('', trim($title));
          $this->assertStringStartsWith('Calificación', $title);
        }
      }
    }
  }

  /**
   * node.title and node_revision.title are both varchar(255). Without the final
   * truncation MySQL would cut the value itself, mid-character on a UTF-8
   * string. This is a guard against a future edit, not a check of today's
   * output.
   */
  public function testTheTitleNeverExceedsTheColumnLength() {
    $title = myapi_service_rating_title(str_repeat('á', 400), 5, $this->created());

    $this->assertLessThanOrEqual(255, drupal_strlen($title));
  }

  /**
   * The date segment resolver on its own, which is where "what counts as a
   * date" is decided once for the title.
   */
  public function testTitleTimestampAcceptsIntegersAndDateStringsOnly() {
    $this->assertSame($this->created(), myapi_service_rating_title_timestamp($this->created()));
    $this->assertSame($this->created(), myapi_service_rating_title_timestamp((string) $this->created()));
    $this->assertNotNull(myapi_service_rating_title_timestamp('2026-08-28 09:14:00'));

    foreach ([NULL, '', 0, '0', -1, 'not a date', [], TRUE] as $created) {
      $this->assertNull(
        myapi_service_rating_title_timestamp($created),
        var_export($created, TRUE) . ' must not resolve to a date.'
      );
    }
  }

  /* -------------------------------------------------------------------------
   * The four hook branches, read out of myapi.module as text.
   *
   * None of them can be executed here — they node_load() and node_save() — but
   * their ABSENCE is the failure mode that costs most: the counters go stale in
   * silence and nobody notices until a provider's reputation is visibly wrong.
   * ---------------------------------------------------------------------- */

  /**
   * Without this branch a rating is created all the same, with title = '' — the
   * blank link in /admin/content this generator exists to prevent.
   */
  public function testNodePresaveDelegatesTheRatingTitle() {
    $presave = $this->functionSource('myapi_node_presave');

    $this->assertStringContainsString("if (\$node->type === 'service_rating') {", $presave);
    $this->assertStringContainsString('myapi_service_rating_set_title($node);', $presave);
  }

  /**
   * The insert branch is what makes a rating count at all — including one an
   * operator writes by hand, which is the whole reason the sync hangs off the
   * hook and not off the close endpoint.
   */
  public function testNodeInsertSyncsTheProviderCounters() {
    $insert = $this->functionSource('myapi_node_insert');

    $this->assertStringContainsString("if (\$node->type === 'service_rating') {", $insert);
    $this->assertStringContainsString('myapi_service_rating_sync_provider(', $insert);
  }

  /**
   * The update branch, so editing the stars from node/%nid/edit resynchronises
   * exactly like creating does.
   */
  public function testNodeUpdateSyncsTheProviderCounters() {
    $update = $this->functionSource('myapi_node_update');

    $this->assertStringContainsString("if (\$node->type === 'service_rating') {", $update);
    $this->assertStringContainsString('myapi_service_rating_sync_provider(', $update);
  }

  /**
   * The delete branch, AND its second argument. Moderating a rating means
   * DELETING it, so with no branch here every act of moderation would leave the
   * reputation stale. And hook_node_delete() runs BEFORE the row goes away, so
   * without $node->nid travelling as $exclude_nid the recalculation would
   * return the very numbers that stood before the deletion — a branch that
   * looks right and does nothing.
   */
  public function testNodeDeleteSyncsTheProviderCountersExcludingTheDyingRating() {
    $delete = $this->functionSource('myapi_node_delete');

    $this->assertStringContainsString("if (\$node->type === 'service_rating') {", $delete);
    $this->assertStringContainsString('myapi_service_rating_sync_provider(', $delete);
    $this->assertStringContainsString('$node->nid', $delete);
  }

  /**
   * NO 'provider' BRANCH IN ANY NODE HOOK. What the sync saves is a 'provider'
   * node; a branch reacting to that bundle would close the loop and recurse.
   * Whoever adds one has to break this test on purpose.
   */
  public function testNoNodeHookReactsToTheProviderBundle() {
    foreach (['myapi_node_presave', 'myapi_node_insert', 'myapi_node_update', 'myapi_node_delete'] as $hook) {
      $this->assertStringNotContainsString(
        "if (\$node->type === 'provider') {",
        $this->functionSource($hook),
        $hook . '() must not react to the provider bundle: the counter sync saves one.'
      );
    }
  }

  /**
   * The route, without which none of the above is reachable from the app.
   */
  public function testTheCloseRouteIsRegistered() {
    $module = file_get_contents(__DIR__ . '/../../myapi.module');

    $this->assertStringContainsString("\$items['api/v1/service-requests/%/close']", $module);
    $this->assertStringContainsString("'myapi_service_request_close_dispatch'", $module);
  }

  /**
   * The include has to be declared in myapi.info, or Drupal never loads it and
   * every one of the branches above fatals on a missing function.
   */
  public function testTheIncludeIsDeclaredInTheInfoFile() {
    $info = file_get_contents(__DIR__ . '/../../myapi.info');

    $this->assertStringContainsString('files[] = includes/myapi.service_rating.inc', $info);
  }

  /**
   * The body of one function of myapi.module, from its declaration to the next
   * one — enough to assert what a single hook does and does not contain.
   *
   * @param string $name
   *
   * @return string
   */
  private function functionSource($name) {
    $module = file_get_contents(__DIR__ . '/../../myapi.module');
    $start = strpos($module, 'function ' . $name . '(');
    $this->assertNotFalse($start, $name . '() must exist in myapi.module.');

    $end = strpos($module, "\n}\n", $start);
    $this->assertNotFalse($end, $name . '() must be closed.');

    return substr($module, $start, $end - $start);
  }

}
